import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {measureShape,vertices,transformShape} from '../src/playgroundMath.mjs';
const {build}=createRequire(createRequire(import.meta.url).resolve('vite'))('esbuild');
const result=await build({stdin:{contents:"export {topics} from './data';export {formulas,formulaDomains} from './formulaCatalog';export {labGroups} from './labGroups';export {newLabLearning} from './newLabLearning';export {admissible} from './situations';export {calculate} from './formulaMath.mjs';export {microConcepts} from './concepts';",resolveDir:fileURLToPath(new URL('../src/',import.meta.url)),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});
const {topics,formulas,labGroups,newLabLearning,admissible,microConcepts}=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
test('Every focused lab has its own formula, valid examples and valid activity targets',()=>{assert.ok(topics.length>=250);assert.equal(new Set(topics.map(t=>t.id)).size,topics.length);const focused=topics.filter(t=>t.id.startsWith('lab-focus-'));assert.equal(focused.length,formulas.length);for(const t of focused){const group=labGroups[t.id];assert.equal(group.formulaIds.length,1);const f=formulas.find(f=>f.id===group.formulaIds[0]);const pack=newLabLearning(t);assert.equal(t.formula,f.tex);assert.equal(t.difficulty,f.difficulty);assert.ok(microConcepts.some(c=>c.engine===t.id));for(const ex of pack.examples)assert.ok(admissible(f,Object.fromEntries(Object.entries(ex.params).filter(([k])=>k!=='formulaId'))),t.id+' example');assert.ok(admissible(f,Object.fromEntries(Object.entries(pack.practice.target).filter(([k])=>k!=='formulaId'))),t.id+' practice');assert.ok(admissible(f,Object.fromEntries(Object.entries(pack.experiment.after).filter(([k])=>k!=='formulaId'))),t.id+' prediction');assert.equal(new Set(pack.experiment.choices).size,3,t.id+' choices')}});
test('New polygon tools have correct areas and scale under transformations',()=>{const mk=kind=>({kind,a:[0,0],b:[160,120],sides:5});assert.equal(measureShape(mk('Square')).area,16);assert.equal(measureShape(mk('Parallelogram')).area,9);assert.equal(measureShape(mk('Trapezium')).area,9);assert.equal(measureShape(mk('Rhombus')).area,6);assert.equal(measureShape(mk('Kite')).area,6);const triangle={kind:'Equilateral triangle',a:[0,0],b:[80,0]};assert.ok(Math.abs(measureShape(triangle).area-3*Math.sqrt(3))<1e-9);assert.equal(vertices(mk('Star')).length,10);for(const kind of ['Star','Square','Rhombus','Kite','Sector','Annulus']){const s=mk(kind);assert.ok(Math.abs(measureShape(transformShape(s,'enlarge')).area-measureShape(s).area*2.25)<1e-8,kind)}});
test('Arc, sector, semicircle and annulus measures match their geometric definitions',()=>{const mk=kind=>({kind,a:[0,0],b:[80,0],sweep:90,innerRatio:.5});assert.ok(Math.abs(measureShape(mk('Arc')).length-Math.PI)<1e-9);assert.ok(Math.abs(measureShape(mk('Sector')).area-Math.PI)<1e-9);assert.ok(Math.abs(measureShape(mk('Semicircle')).area-2*Math.PI)<1e-9);assert.ok(Math.abs(measureShape(mk('Annulus')).area-3*Math.PI)<1e-9)});

