export const programmeLevels = [
  [
    3,
    "Number Sense Explorer",
    [
      "Place-value detective",
      "Number-line routes",
      "Compare and order",
      "Rounding and estimation",
      "Number patterns",
    ],
  ],
  [
    3,
    "Operations and Patterns Explorer",
    [
      "Addition strategies",
      "Subtraction strategies",
      "Multiplication arrays",
      "Division and remainders",
      "Pattern puzzles",
    ],
  ],
  [
    4,
    "Number Builder",
    [
      "Build larger numbers",
      "Factors and multiples",
      "Division algorithm",
      "Mental arithmetic",
      "Estimation checks",
    ],
  ],
  [
    4,
    "Fraction and Shape Explorer",
    [
      "Equal shares",
      "Equivalent fractions",
      "Compare fractions",
      "Angles and turns",
      "Shape and symmetry",
    ],
  ],
  [
    5,
    "Number Extension Builder",
    [
      "Decimal place value",
      "Fraction operations",
      "Common multiples",
      "Decimal operations",
      "Number-system connections",
    ],
  ],
  [
    5,
    "Applied Maths Explorer",
    [
      "Perimeter design",
      "Area planning",
      "Volume and nets",
      "Time and money decisions",
      "Read and compare data",
    ],
  ],
  [
    6,
    "Number Systems and Ratio Explorer",
    [
      "Integers on a line",
      "Rational comparisons",
      "Prime factorisation",
      "Ratios and unit rates",
      "Proportional recipes",
    ],
  ],
  [
    6,
    "Algebra and Geometry Builder",
    [
      "Translate an expression",
      "Balance an equation",
      "Angle relationships",
      "Triangle constructions",
      "Measurement problems",
    ],
  ],
  [
    7,
    "Rational and Power Builder",
    [
      "Rational operations",
      "Exponent rules",
      "Squares and roots",
      "Scale and proportion",
      "Algebraic reasoning",
    ],
  ],
  [
    7,
    "Application and Data Builder",
    [
      "Percent change",
      "Money models",
      "Circle measurement",
      "Statistics choices",
      "Probability experiments",
    ],
  ],
  [
    8,
    "Pre-Secondary Numbers and Algebra",
    [
      "Number-system structure",
      "Powers and roots",
      "Linear equations",
      "Identities with tiles",
      "Factorisation reasoning",
    ],
  ],
  [
    8,
    "Graph and Geometry Builder",
    [
      "Coordinates and routes",
      "Graph transformations",
      "Quadrilateral properties",
      "Solid measurement",
      "Compare growth models",
    ],
  ],
  [
    9,
    "Secondary Core Concepts",
    [
      "Real-number reasoning",
      "Polynomial values",
      "Linear equation graphs",
      "Triangle and circle geometry",
      "Heron and solids",
    ],
  ],
  [
    9,
    "Proof and Problem-Solving Bridge",
    [
      "Explain a counterexample",
      "Similarity and congruence",
      "Rearrangement proof",
      "Coordinate arguments",
      "Mixed competition problems",
    ],
  ],
] as const;
const links: Record<string, string> = {
  "Place-value detective": "place",
  "Number-line routes": "number",
  "Compare and order": "number",
  "Rounding and estimation": "lab-estimation",
  "Number patterns": "lab-number-patterns",
  "Addition strategies": "addition",
  "Subtraction strategies": "addition",
  "Multiplication arrays": "array",
  "Division and remainders": "division",
  "Pattern puzzles": "lab-number-patterns",
  "Build larger numbers": "place",
  "Factors and multiples": "factors",
  "Division algorithm": "division",
  "Mental arithmetic": "lab-number-bonds",
  "Estimation checks": "lab-estimation",
  "Equal shares": "fraction",
  "Equivalent fractions": "fraction",
  "Compare fractions": "fraction",
  "Angles and turns": "angle",
  "Shape and symmetry": "triangle",
  "Decimal place value": "decimal",
  "Fraction operations": "lab-fraction-operations",
  "Common multiples": "factors",
  "Decimal operations": "decimal",
  "Number-system connections": "number",
  "Perimeter design": "area",
  "Area planning": "area",
  "Volume and nets": "net",
  "Time and money decisions": "commercial",
  "Read and compare data": "statistics",
  "Integers on a line": "number",
  "Rational comparisons": "fraction",
  "Prime factorisation": "factors",
  "Ratios and unit rates": "ratio",
  "Proportional recipes": "lab-proportion",
  "Translate an expression": "balance",
  "Balance an equation": "balance",
  "Angle relationships": "angle",
  "Triangle constructions": "triangle",
  "Measurement problems": "area",
  "Rational operations": "lab-fraction-operations",
  "Exponent rules": "lab-powers",
  "Squares and roots": "lab-powers",
  "Scale and proportion": "ratio",
  "Algebraic reasoning": "lab-identities",
  "Percent change": "lab-percent-change",
  "Money models": "commercial",
  "Circle measurement": "lab-focus-circle-area",
  "Statistics choices": "statistics",
  "Probability experiments": "probability",
  "Number-system structure": "number",
  "Powers and roots": "lab-powers",
  "Linear equations": "balance",
  "Identities with tiles": "lab-identities",
  "Factorisation reasoning": "lab-polynomials",
  "Coordinates and routes": "coordinate",
  "Graph transformations": "graph",
  "Quadrilateral properties": "lab-quadrilaterals",
  "Solid measurement": "solid",
  "Compare growth models": "lab-compound",
  "Real-number reasoning": "lab-surds",
  "Polynomial values": "lab-polynomials",
  "Linear equation graphs": "graph",
  "Triangle and circle geometry": "triangle",
  "Heron and solids": "lab-triangle-measurement",
  "Explain a counterexample": "triangle",
  "Similarity and congruence": "triangle",
  "Rearrangement proof": "pythagoras",
  "Coordinate arguments": "coordinate",
  "Mixed competition problems": "lab-counting",
};
export const competitiveProgramme = programmeLevels.map(
  ([grade, title, chapters], i) => ({
    id: "programme-" + (i + 1),
    classNumber: grade,
    level: i % 2 ? "B" : "A",
    number: i + 1,
    title,
    focus:
      i % 2
        ? "Applications, justified strategies and competitive foundations"
        : "Concept building and mathematical foundations",
    chapters: chapters.map((name, j) => ({
      id: `programme-${i + 1}/chapter-${j + 1}`,
      title: name,
      labId: links[name],
      status: "linked core lab; chapter-specific extension needs review",
    })),
  }),
);
