import ClassExplorer from './ClassExplorer';
import {useState,useEffect,lazy,Suspense,Component,type ReactNode} from 'react';
import {BarChart3,Home,Layers,Grid2X2,Sparkles,Sigma,Search,Box,ChevronRight,ArrowUpRight,ArrowRight,Maximize,Minimize,RotateCcw,Menu,X,SlidersHorizontal,GraduationCap,Clock,FlaskConical,Compass,BookOpen,Check,Sun,Moon} from 'lucide-react';
import {motion,MotionConfig} from 'framer-motion';
import {topics,domains,boards,navigation,labNavigation,curriculum,type Topic} from './data';
import {Formula} from './components';
import {conceptsFor} from './concepts';
const TopicExperience=lazy(()=>import('./discovery/DiscoveryJourney'));
const CurriculumNavigator=lazy(()=>import('./discovery/CurriculumNavigator'));
const Studios=lazy(()=>import('./discovery/Studios'));
const GraphStudio=lazy(()=>import('./discovery/GraphStudio'));
const FoundationStudio=lazy(()=>import('./discovery/FoundationStudio'));



const OtherLabs=lazy(()=>import('./Labs'));
const FormulaLibrary=lazy(()=>import('./FormulaExplorer'));
const RealWorld=lazy(()=>import('./RealWorld'));
const Challenges=lazy(()=>import('./Challenges'));
const Analytics=lazy(()=>import('./Analytics'));
const HeroScene=lazy(()=>import('./HeroScene'));
const Playground=lazy(()=>import('./AdvancedPlayground'));
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function save(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
const navIcons:Record<string,typeof Home>={home:Home,layers:Layers,grid:Grid2X2,sparkles:Sparkles,sigma:Sigma,chart:BarChart3};
class LabBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="empty"><h3>This visualization could not load.</h3><p>Try reloading, or use another lab. Your browser may not support WebGL.</p><button onClick={()=>window.location.reload()}>Reload app</button></div>:this.props.children}}
export default function App(){const [view,setView]=useState('home'),[catalogLimit,setCatalogLimit]=useState(36),[active,setActive]=useState<Topic|null>(null),[query,setQuery]=useState(''),[classFilter,setClassFilter]=useState('All'),[domain,setDomain]=useState('All'),[kind,setKind]=useState('All'),[difficulty,setDifficulty]=useState('All'),[board,setBoard]=useState('All'),[tab,setTab]=useState('Interact'),[recent,setRecent]=useState<string[]>(()=>read('vx-recent',[])),[classroom,setClassroom]=useState(false),[menu,setMenu]=useState(false),[dark,setDark]=useState(()=>read('vx-dark',false)),[resetKey,setResetKey]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState('');
useEffect(()=>{setCatalogLimit(36)},[query,classFilter,domain,difficulty,kind,view]);
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';save('vx-dark',dark)},[dark]);
useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[view,active?.id]);
useEffect(()=>{const listen=()=>{if(!document.fullscreenElement)setClassroom(false)};document.addEventListener('fullscreenchange',listen);const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);setClassroom(false)};if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('#global-search')?.focus()}};window.addEventListener('keydown',key);return()=>{document.removeEventListener('fullscreenchange',listen);window.removeEventListener('keydown',key)}},[]);
useEffect(()=>{const sync=()=>{const id=location.hash.slice(1).split('?')[0];const t=topics.find(x=>x.id===id);if(t){setActive(t);setView('topic')}else{setActive(null);setView(['classes','domains','formulas','playground','analytics','recent','real','games','catalog','curriculum','programme','studios','graph-studio'].includes(id)||id.startsWith('foundation-')?id:'home')}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
const go=(v:string)=>{setView(v);setActive(null);setMenu(false);setQuery('');setDomain('All');setClassFilter('All');setKind('All');setDifficulty('All');setBoard('All');location.hash=v};
const open=(t:Topic)=>{setActive(t);setView('topic');setTab('Interact');setQuery('');setMenu(false);setAnswer('');setFeedback('');setResetKey(k=>k+1);location.hash=t.id;const next=[t.id,...recent.filter(x=>x!==t.id)].slice(0,8);setRecent(next);save('vx-recent',next)};
const fullscreen=async()=>{if(classroom){setClassroom(false);if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{})}else{setClassroom(true);await document.documentElement.requestFullscreen?.().catch(()=>{})}};
const filtered=topics.filter(t=>(classFilter==='All'||t.classes.includes(Number(classFilter)))&&(domain==='All'||t.domain===domain)&&(['All','2D','3D','Interactive'].includes(kind))&&(difficulty==='All'||t.difficulty===difficulty)&&(view!=='recent'||recent.includes(t.id))&&(`${t.title} ${t.domain} ${t.unit} ${t.subtopic} ${t.micro} ${conceptsFor(t.id).map(c=>c.label).join(' ')} ${t.formula} ${t.real} ${t.learn} ${t.keywords.join(' ')} ${t.classes.map(n=>`class ${n}`).join(' ')}`.toLowerCase().includes(query.toLowerCase())));
const catalog=(heading:string)=> <><div className="section-heading"><div><span className="eyebrow">YOUR NEXT DISCOVERY</span><h1>{heading}</h1><p>Find a concept. Open a lab. Make it click.</p></div><span className="count-pill">{filtered.length} interactive labs</span></div><div className="filters"><SlidersHorizontal size={18}/>{[['Class',classFilter,setClassFilter,['All',...Array.from({length:12},(_,i)=>String(i+1))]],['Domain',domain,setDomain,['All',...domains]],['Visualization',kind,setKind,['All','2D','3D','Interactive']],['Difficulty',difficulty,setDifficulty,['All','Foundation','Beginner','Intermediate','Advanced']],['Curriculum',board,setBoard,boards]].map(([label,value,set,options])=><label key={label as string}><small>{label as string}</small><select aria-label={label as string} value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}>{(options as string[]).map(o=><option key={o}>{o}</option>)}</select></label>)}</div>{board!=='All'&&<p className="mapping-note">{board} · {curriculum.status}. Check your school’s current syllabus for exact coverage.</p>}<>{classFilter!=='All'&&<CurriculumTree topics={filtered} classNumber={classFilter} onOpen={open}/>}<div className="topic-grid">{filtered.slice(0,catalogLimit).map(t=><TopicCard key={t.id} topic={t} onOpen={()=>open(t)}/>)}</div>{catalogLimit<filtered.length&&<button className="primary atlas-load" onClick={()=>setCatalogLimit(n=>n+36)}>Show 36 more labs · {filtered.length-catalogLimit} remaining</button>}</>{!filtered.length&&<div className="empty"><Search size={30}/><h3>No matching labs</h3><p>Try a broader search or clear your filters.</p><button onClick={()=>{setQuery('');setDomain('All');setClassFilter('All');setKind('All');setDifficulty('All')}}>Clear filters</button></div>}</>;
return <MotionConfig reducedMotion="user"><div className={`app ${classroom?'classroom':''}`}><aside className={`sidebar ${menu?'open':''}`}><a className="brand" href="#home" onClick={()=>go('home')}><div className="brand-mark"><Box size={24}/></div><div>Visionic<span>X</span><small>MATHS ATLAS</small></div></a><button className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setMenu(false)}><X size={20}/></button><span className="sidebar-label">DISCOVER</span><nav>{navigation.map(n=>{const Icon=navIcons[n.icon];return <button key={n.mode} className={view===n.mode?'active':''} onClick={()=>go(n.mode)}><Icon size={18}/>{n.label}{view===n.mode&&<i/>}</button>})}</nav><span className="sidebar-label">DISCOVERY PLATFORM</span><nav>{[["Curriculum & coverage","curriculum"],["14-level programme","programme"],["16 learning studios","studios"],["Graph Studio","graph-studio"]].map(([label,id])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><BookOpen size={18}/>{label}</button>)}</nav><span className="sidebar-label labs-label">YOUR LABS <span>{topics.length}</span></span><nav className="labs-nav">{labNavigation.map(([label,d])=><button key={label} className={active?.domain===d?'active':''} onClick={()=>{go('catalog');setDomain(d)}}><span className="nav-dot"/>{label}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>go('recent')}><Clock size={17}/>Recently explored</button><button onClick={()=>go('real')}><Compass size={17}/>Real-world mathematics</button><button onClick={()=>go('games')}><Sparkles size={17}/>Math challenges</button><div className="sidebar-note"><FlaskConical size={24}/><p>A little curiosity.<br/><strong>A whole lot of possibility.</strong></p></div></div></aside>{menu&&<div className="nav-scrim" onClick={()=>setMenu(false)}/>}
<div className="app-content"><header className="topbar"><button className="mobile-toggle icon-button" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={21}/></button><div className="top-breadcrumb">Maths Atlas <ChevronRight size={14}/><strong>{active?.title||({home:'Overview',classes:'Classes',domains:'Domains',formulas:'Formula library',playground:'Playground',analytics:'Learning analytics'}[view]||'Explore')}</strong></div><div className="search-box"><Search size={17}/><input id="global-search" aria-label="Search Mathematics" placeholder="Search mathematics…" value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value){setActive(null);setView('search')}}}/><kbd>Ctrl K</kbd>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}</div><button className="icon-button" aria-label={dark?'Switch to light theme':'Switch to dark theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><div className="student-avatar">VX</div></header>
<main>{view==='home'&&!query?<><div className="welcome-line"><span><span className="live-dot"/>YOUR CURIOSITY STARTS HERE</span><span className="tiny">Foundations · Classes 1–12</span></div><section className="hero"><div className="hero-copy"><div className="hero-pill"><Sparkles size={14}/> A new dimension of learning</div><h1>See mathematics.<br/><em>Discover the why.</em></h1><p>Build it. Derive it. Use it. Master it.<br className="desktop-only"/> A connected journey from first numbers to calculus.</p><div className="hero-actions"><button className="primary" onClick={()=>open(topics.find(t=>t.id==='lab-focus-circle-area')!)}>Start discovering <ArrowRight size={17}/></button><button className="text-button" onClick={()=>go('curriculum')}>Find your path <ChevronRight size={16}/></button></div><div className="hero-proof"><span><Box size={16}/> 2D & 3D experiments</span><span><Check size={15}/> Learn by doing</span></div></div><Suspense fallback={<div className="hero-scene-loading">Preparing your mathematical universe…</div>}><LabBoundary><HeroScene/></LabBoundary></Suspense><div className="hero-art-caption"><i/>DRAG TO ORBIT · IDEAS COME TO LIFE</div></section>
<div className="home-stats"><div><Box size={19}/><strong>{topics.length}</strong><span>interactive labs</span></div><div><GraduationCap size={20}/><strong>12</strong><span>classes, one journey</span></div><div><Compass size={19}/><strong>{domains.length}</strong><span>mathematical domains</span></div><div><Sparkles size={19}/><strong>∞</strong><span>ways to wonder</span></div></div>
<a className="home-journey-link" href="#analytics"><span>From your first number to advanced mathematics</span><strong>Explore the VisionicX learning journey <ArrowUpRight size={17}/></strong></a><div className="section-heading compact"><div><h2>Where will you explore today?</h2><p>Big ideas. Hands-on discoveries.</p></div><button className="text-button" onClick={()=>go('catalog')}>View all labs <ArrowUpRight size={17}/></button></div><div className="featured-grid">{['fraction','solid','graph','trig'].map(id=><TopicCard key={id} topic={topics.find(t=>t.id===id)!} onOpen={()=>open(topics.find(t=>t.id===id)!)} featured/>)}</div>
<div className="section-heading compact"><div><h2>A lab for every stage</h2><p>Follow your class. Or follow your curiosity.</p></div><button className="text-button" onClick={()=>go('classes')}>Explore curriculum <ArrowUpRight size={17}/></button></div><div className="class-strip">{Array.from({length:12},(_,i)=><button key={i} onClick={()=>{go('catalog');setClassFilter(String(i+1));save('vx-last-class',i+1)}}><small>CLASS</small><strong>{String(i+1).padStart(2,'0')}</strong></button>)}</div><div className="discovery-banner"><div className="banner-icon"><LightIcon/></div><div><span className="eyebrow">THE BEAUTY IS IN THE WHY</span><h3>What happens if you change just one thing?</h3><p>Pull a slider. Move a point. Unfold a shape. That’s where understanding begins.</p></div><button onClick={()=>go('playground')}>Open playground <ArrowRight size={17}/></button></div></>:
view==='topic'&&active?<><div className="topic-breadcrumb"><button onClick={()=>{go('catalog');setClassFilter(String(active.classes[0]))}}>Class {active.classes[0]}</button><ChevronRight size={13}/><span>{active.domain}</span><ChevronRight size={13}/><span>{active.unit}</span><ChevronRight size={13}/><strong>{active.micro}</strong></div><div className="topic-heading"><div><span className="eyebrow">{active.domain.toUpperCase()} · {active.id==='lab-focus-circle-area'?'DISCOVERY CHAPTER':'2D + 3D LINKED LAB'}</span><h1>{active.title}</h1><p>{active.subtitle.replace(/\.$/,'')}. Change something. Discover something.</p></div><div className="topic-actions"><button className="secondary" onClick={()=>setResetKey(k=>k+1)}><RotateCcw size={16}/>Reset</button><button className="primary" onClick={fullscreen}>{classroom?<Minimize size={17}/>:<Maximize size={17}/>}<span>{classroom?'Exit classroom':'Classroom mode'}</span></button></div></div><LabBoundary key={`${active.id}-${resetKey}`}><Suspense fallback={<div className="loading">Preparing your guided lesson…</div>}><TopicExperience topic={active} onOpen={open}/></Suspense></LabBoundary><div className="topic-footer"><span><span className="live-dot"/>All calculations happen on your device</span><span>{active.classes.map(c=>`Class ${c}`).join(' · ')}</span></div></>:
['curriculum','programme','studios','graph-studio'].includes(view)||view.startsWith('foundation-')?<Suspense fallback={<div className="loading">Opening discovery workspace…</div>}>{view==='curriculum'?<CurriculumNavigator/>:view==='programme'?<CurriculumNavigator programme/>:view==='studios'?<Studios/>:view==='graph-studio'?<GraphStudio/>:<FoundationStudio key={view} id={view}/>}</Suspense>:
view==='analytics'?<Suspense fallback={<div className="loading">Preparing learning analytics…</div>}><Analytics/></Suspense>:
view==='classes'?<ClassExplorer onOpen={open} onCatalog={(grade)=>{go('catalog');setClassFilter(String(grade));setDomain('All')}}/>:
view==='domains'?<><div className="section-heading"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h1>Connected by mathematics</h1><p>Explore ideas across classes and see how they connect.</p></div></div><div className="domains-grid">{domains.map((d,i)=><button key={d} onClick={()=>{go('catalog');setDomain(d)}}><span className="domain-number">{String(i+1).padStart(2,'0')}</span><h2>{d}</h2><p>{topics.filter(t=>t.domain===d).map(t=>t.subtitle).join(' · ')}</p><span>{topics.filter(t=>t.domain===d).length} interactive labs <ArrowRight size={16}/></span></button>)}</div></>:
view==='formulas'?<Suspense fallback={<div className="loading">Opening the visual formula atlas…</div>}><FormulaLibrary/></Suspense>:
view==='playground'?<><div className="section-heading"><div><span className="eyebrow">A SPACE FOR YOUR IDEAS</span><h1>Math playground</h1><p>Draw, drag, measure, and discover.</p></div></div><Suspense fallback={<div className="loading">Opening your workspace…</div>}><Playground/></Suspense></>:
view==='real'?<Suspense fallback={<div className="loading">Preparing real-world situations…</div>}><RealWorld/></Suspense>:
view==='games'?<Suspense fallback={<div className="loading">Preparing your challenges…</div>}><Challenges/></Suspense>:catalog(query?`Results for “${query}”`:view==='recent'?'Pick up where you left off':classFilter!=='All'?`Class ${classFilter} curriculum explorer`:domain!=='All'?domain:'Explore the mathematics lab')}
</main><footer className="site-footer"><span>VisionicX <b>·</b> See it. Change it. Understand it.</span><span>Made for curious minds.</span></footer></div></div></MotionConfig>}
function CurriculumTree({topics:items,classNumber,onOpen}:{topics:Topic[];classNumber:string;onOpen:(t:Topic)=>void}){return <section className="curriculum-tree"><div className="eyebrow">CLASS {classNumber} · CONCEPT PATHS</div><p>Open a unit to follow its topics, subtopics, and experiments.</p>{[...new Set(items.map(t=>t.domain))].map(d=><details key={d}><summary>{d}<span>{items.filter(t=>t.domain===d).length} labs</span></summary>{items.filter(t=>t.domain===d).map(t=><details key={t.id}><summary>{t.unit}</summary><details><summary>{t.title}</summary><div className="concept-leaf"><span>{t.subtopic}</span><ArrowRight size={14}/><span>{conceptsFor(t.id).map(c=>c.label).join(' · ')}</span><button onClick={()=>onOpen(t)}>Open interactive lab <ArrowUpRight size={14}/></button></div></details></details>)}</details>)}</section>}
function LightIcon(){return <FlaskConical size={26}/>}
function TopicCard({topic:t,onOpen,featured=false}:{topic:Topic;onOpen:()=>void;featured?:boolean}){return <motion.button whileHover={{y:-4}} className={`topic-card ${featured?'featured':''} art-${t.id}`} onClick={onOpen}><div className="card-art"><MiniArt id={t.id}/><span className="art-badge">2D + 3D</span></div><div className="card-copy"><span className="eyebrow">{t.domain}</span><h3>{t.title}</h3><p>{t.subtitle}</p><div className="card-meta"><span>Class {t.classes[0]}{t.classes.length>1?`–${t.classes[t.classes.length-1]}`:''}</span><ArrowUpRight size={18}/></div></div></motion.button>}
function MiniArt({id}:{id:string}){const topic=topics.find(t=>t.id===id);if(id.startsWith('lab-')){id=topic?.domain==='3D Geometry'?'solid':topic?.domain==='Trigonometry'||topic?.domain==='Geometry'?'circle':topic?.domain==='Numbers'||topic?.domain==='Arithmetic'?'number':topic?.domain==='Fractions'?'fraction':id}return <svg viewBox="0 0 240 140" aria-hidden="true">{id==='number'?<g>{Array.from({length:15},(_,i)=><rect key={i} x={62+i%5*25} y={36+Math.floor(i/5)*25} width="19" height="19" rx="4" fill={i<10?'#84a78a':'#dec08a'}/>)}</g>:id==='fraction'?<g transform="translate(120 73)"><circle r="45" fill="#d7e6dc"/>{[0,1,2].map(i=><path key={i} d="M0 0 L0 -45 A45 45 0 0 1 45 0 Z" fill="#669682" stroke="#eaf0e9" strokeWidth="3" transform={`rotate(${i*90})`}/>)}<circle r="6" fill="#eaf0e9"/></g>:['solid','net','volume','vector','conic'].includes(id)?<g transform="translate(70 20)"><path d="M50 0L100 28L100 88L50 116L0 88L0 28Z" fill="#ebd5b3" stroke="#bd955b" strokeWidth="1.5"/><path d="M0 28L50 57L100 28M50 57V116M50 0V57" stroke="#bd955b" fill="none" strokeWidth="1.5"/><path d="M0 88L50 57L100 88" fill="none" stroke="#bd955b" strokeDasharray="4 4"/></g>:id==='trig'||id==='angle'||id==='circle'?<g><circle cx="120" cy="72" r="48" fill="none" stroke="#b7c3c9"/><path d="M70 72H170M120 22V122" stroke="#ccd1d2"/><path d="M120 72L158 43L158 72Z" fill="#9facbd" fillOpacity=".3" stroke="#677d9c" strokeWidth="2"/><circle cx="158" cy="43" r="4" fill="#677d9c"/><text x="132" y="67" fill="#677d9c" fontSize="12">θ</text></g>:<g><path d="M40 112H200M120 20V123" stroke="#c0b8cd"/>{[60,80,100,140,160,180].map(x=><path key={x} d={`M${x} 25V120`} stroke="#ddd6e5"/>)}<path d="M40 36Q120 180 200 36" fill="none" stroke="#927ba9" strokeWidth="3"/><circle cx="158" cy="90" r="4" fill="#927ba9"/></g>}</svg>}
function HeroArt(){return <div className="hero-art"><svg viewBox="0 0 550 340" aria-hidden="true"><defs><linearGradient id="orb" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#9ac0a1"/><stop offset="1" stopColor="#315c47"/></linearGradient><linearGradient id="cube" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#eed7a9"/><stop offset="1" stopColor="#c3a174"/></linearGradient><radialGradient id="shadow"><stop stopColor="#254934" stopOpacity=".16"/><stop offset="1" stopColor="#254934" stopOpacity="0"/></radialGradient></defs><ellipse cx="278" cy="295" rx="195" ry="35" fill="url(#shadow)"/><path d="M45 218L478 88M65 285L495 148M140 326L465 210M88 105L455 310M176 63L510 259M275 43L530 189" stroke="#b4c4ad" strokeOpacity=".28"/><g className="float-slow"><circle cx="219" cy="166" r="76" fill="url(#orb)"/><ellipse cx="219" cy="166" rx="29" ry="76" stroke="#c4d9ba" fill="none" strokeOpacity=".5"/><ellipse cx="219" cy="166" rx="57" ry="76" stroke="#c4d9ba" fill="none" strokeOpacity=".35"/><ellipse cx="219" cy="166" rx="76" ry="22" stroke="#c4d9ba" fill="none" strokeOpacity=".6"/><ellipse cx="219" cy="145" rx="70" ry="20" stroke="#c4d9ba" fill="none" strokeOpacity=".3"/><ellipse cx="219" cy="192" rx="70" ry="20" stroke="#c4d9ba" fill="none" strokeOpacity=".3"/></g><g className="float-alt"><path d="M349 80L419 119L419 197L349 236L279 197L279 119Z" fill="url(#cube)" fillOpacity=".82" stroke="#aa9168"/><path d="M279 119L349 158L419 119M349 158V236" fill="none" stroke="#8f7d59"/><path d="M349 80V158M279 197L349 158L419 197" fill="none" stroke="#a38b60" strokeDasharray="4 3"/><path d="M302 132L372 93M326 145L395 106M302 210V132M326 223V145M372 223V145M395 210V132" stroke="#a58e66" strokeOpacity=".28"/></g><g transform="translate(423 249)"><circle r="35" fill="#d7cabc"/><path d="M0 0L0 -35A35 35 0 1 1 -35 0Z" fill="#b2ad95"/><path d="M0-35V35M-35 0H35" stroke="#eee5d2" strokeWidth="2"/></g><g transform="translate(117 242)"><path d="M0-30L35 25L-35 25Z" fill="#c4ceb7" stroke="#91a286"/><path d="M0-30L0 12L35 25M0 12L-35 25" fill="none" stroke="#91a286"/></g><text x="384" y="58" fill="#6f8570" fontSize="18" fontStyle="italic">a² + b² = c²</text><text x="116" y="77" fill="#839079" fontSize="19" fontStyle="italic">πr²</text><circle cx="458" cy="64" r="3" fill="#93a57a"/><circle cx="98" cy="171" r="3" fill="#93a57a"/><path d="M455 177h12m-6-6v12" stroke="#839777"/></svg></div>}


