import {labGroups} from './labGroups';
import {formulas} from './formulaCatalog';
export type Engine=`lab-${string}`|'fraction'|'number'|'place'|'addition'|'array'|'division'|'percentage'|'ratio'|'balance'|'angle'|'triangle'|'pythagoras'|'circle'|'area'|'solid'|'net'|'volume'|'coordinate'|'graph'|'probability'|'statistics'|'trig'|'conic'|'matrix'|'vector'|'limit'|'derivative'|'integral'|'commercial'|'factors'|'quadratic'|'sequence'|'decimal';
export type Topic={id:Engine; title:string; subtitle:string; domain:string; classes:number[]; unit:string; subtopic:string; micro:string; formula:string; keywords:string[]; kind:string; difficulty:string; learn:string; real:string; task:string; answer:string; tabs:string[]};
const specs:[Engine,string,string,number[],string,string,string,string,string,string,string,string][]=[
['number','Number Line Explorer','Numbers',[1,2,3,6,7],'Position & direction','Locate a number','x \\in \\mathbb{R}','integers counting positive negative ordering','Move a point along the number line. Each step right adds one; each step left subtracts one.','A lift moving between basement and upper floors follows a number line.','How many steps from −3 to 4?','7'],
['place','Place Value Lab','Numbers',[1,2,3,4],'Base-10 blocks','Hundreds, tens & ones','N=100h+10t+u','counting digits blocks decimal','Ten ones make one ten. Ten tens make one hundred. A digit’s position changes its value.','Money bundles and packing boxes both use groups of ten.','What is the value of 7 in 372?','70'],
['addition','Addition & Subtraction','Arithmetic',[1,2,3],'Combining quantities','Joining and taking away','a+b=c','sum difference counting','Join two groups to add. Take away a group to subtract. Watch how the total changes.','Count how many apples remain after sharing some with friends.','What is 8 + 5?','13'],
['array','Multiplication Arrays','Arithmetic',[2,3,4],'Equal groups','Rows × columns','N=r\\times c','multiply product repeated addition','An array arranges equal groups in rows and columns. Swapping rows and columns keeps the total the same.','Seats in a cinema are arranged in rows and columns.','What is 4 × 6?','24'],
['division','Division Sharing Lab','Arithmetic',[2,3,4],'Equal sharing','Quotient & remainder','N=dq+r','divide groups quotient remainder','Share objects one at a time into equal groups. Objects left over form the remainder.','Share sweets fairly among friends.','What is the remainder when 17 is divided by 5?','2'],
['fraction','Fraction Visualizer','Fractions',[3,4,5,6,7],'Parts of a whole','Equal parts & equivalence','\\frac{n}{d}=n\\div d','pizza fraction bar equivalent mixed improper decimal percentage ratio','A fraction counts equal parts. The denominator tells you how many parts make one whole. The numerator tells you how many parts you have.','Share a pizza, measure a recipe, or divide a journey into equal stages.','What numerator makes ?/8 equivalent to 3/4?','6'],
['percentage','Percentage 100-Grid','Fractions',[5,6,7,8],'Parts per hundred','Percentage as a fraction','p\\%=\\frac{p}{100}','percent discount decimal hundred','Each square represents one hundredth of the whole. A percentage counts how many of the hundred squares are selected.','A 25% discount removes one quarter of the original price.','What is 25% of 80?','20'],
['ratio','Ratio & Proportion','Fractions',[6,7,8],'Relative quantities','Scaling equal ratios','a:b=ka:kb','proportion direct scale comparison','A ratio compares quantities. Multiplying both quantities by the same number preserves the relationship.','A recipe using two cups of flour for three cups of milk can be scaled for more people.','Complete the equivalent ratio: 2:3 = 6:?','9'],
['balance','Algebra Balance Scale','Algebra',[6,7,8],'Linear equations','Preserve equality','x+a=b\\Rightarrow x=b-a','variable expression equation solve','An equation is balanced. Removing the same quantity from both sides keeps it balanced and isolates the unknown.','Work out an unknown parcel weight from a balance scale.','Solve x + 3 = 7.','4'],
['angle','Angle Explorer','Geometry',[4,5,6,7],'Angles','Rotation between rays','\\theta+\\phi=180^\\circ','acute right obtuse reflex protractor','An angle measures rotation from one ray to another. A full turn is 360 degrees.','A door hinge and the hands of a clock create changing angles.','What complements a 35° angle?','55'],
['triangle','Triangle Explorer','Geometry',[5,6,7,9,10],'Triangles','Vertices, sides & angles','A=\\frac12 bh','triangle congruence similarity centroid scalene equilateral isosceles','Move the vertices and watch the sides, area and angles change. The interior angles of any nondegenerate triangle add to 180 degrees.','Triangular frames give bridges and roofs structural rigidity.','What is the third angle if two are 50° and 60°?','70'],
['pythagoras','Pythagoras Visual Proof','Geometry',[7,8,9,10],'Right triangles','Squares on three sides','a^2+b^2=c^2','triangle hypotenuse theorem proof squares','For a right triangle, the square on the hypotenuse equals the sum of the squares on the legs. Rearrange four identical triangles to reveal the identity.','Find the length of a ladder needed to reach a window.','A right triangle has legs 3 and 4. Find its hypotenuse.','5'],
['circle','Circle Explorer','Geometry',[5,6,7,9,10],'Circles','Radius & circumference','A=\\pi r^2,\\quad C=2\\pi r','diameter chord tangent arc sector','All points on a circle are the same distance from the centre. That distance is the radius.','Wheel circumference tells you how far a bicycle travels in one revolution.','What is the diameter of a circle with radius 6?','12'],
['area','Area & Perimeter Lab','Mensuration',[3,4,5,6,7],'Plane measurement','Covering & boundary','A=lw,\\quad P=2(l+w)','rectangle square area perimeter length width','Area counts the unit squares inside a shape. Perimeter measures the length around its boundary.','Area determines tiles needed for a floor; perimeter determines fencing.','Find the area of a 6 by 4 rectangle.','24'],
['solid','3D Solids Explorer','3D Geometry',[5,6,7,8,9,10],'Solid shapes','Faces, edges & dimensions','V_{cube}=s^3','cube sphere cone cylinder prism pyramid transparent rotate','Rotate a solid to inspect its shape from every side. Change dimensions to see how volume and surface area grow.','Boxes, cans and balls are examples of solids around us.','How many faces does a cube have?','6'],
['net','Nets Fold / Unfold','3D Geometry',[5,6,7,8],'Nets of solids','From six squares to a cube','SA_{cube}=6s^2','cube fold unfold net faces','A net is a flat arrangement of faces that folds into a solid. Six equal squares can form a cube when connected in a suitable pattern.','A cardboard box is cut from a net before it is folded.','How many equal squares are in a cube net?','6'],
['volume','Surface Area & Volume','3D Geometry',[7,8,9,10],'Solid measurement','Covering & filling','V_{cylinder}=\\pi r^2h','mensuration surface sphere cylinder cone cube','Surface area measures the outside of a solid. Volume measures the space inside it.','Estimate how much paint covers a tank and how much water fills it.','Find the volume of a cube with side 3.','27'],
['coordinate','Coordinate Geometry Lab','Coordinate Geometry',[6,7,8,9,10],'Cartesian plane','Ordered pairs','d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}','point quadrant origin distance midpoint slope','The first coordinate moves horizontally; the second moves vertically. Drag a point and read its ordered pair.','Map positions use coordinates to describe exact locations.','Which quadrant contains (3, 4)? Enter 1–4.','1'],
['graph','Dynamic Graph Lab','Functions',[8,9,10,11],'Function graphs','Parameters & transformations','y=mx+c','linear quadratic polynomial sin slope intercept','A function connects an input x to an output y. Parameters change the graph in predictable ways.','Graphs show relationships such as time and distance.','In y = 2x + 3, what is y when x = 4?','11'],
['probability','Probability Simulator','Probability',[6,7,8,9,10,11,12],'Random experiments','Relative frequency','P(E)=\\frac{\\text{favourable outcomes}}{\\text{total outcomes}}','coin dice trials experimental theoretical random','Every trial is random. As trials accumulate, experimental relative frequencies tend to stabilise near their theoretical probabilities.','Repeated games reveal whether a coin or die behaves fairly.','For a fair six-sided die, how many outcomes are even?','3'],
['statistics','Statistics Visualizer','Statistics',[5,6,7,8,9,10,11],'Data & averages','Distribution and centre','\\bar{x}=\\frac{\\sum x_i}{n}','mean median mode range variance standard deviation data','Mean is a balance point, median is the middle value, and mode is the most frequent value. These describe different aspects of the same data.','Compare cricket scores, daily temperatures or the heights of classmates.','Find the mean of 2, 4 and 6.','4'],
['trig','Triangle + Unit Circle','Trigonometry',[10,11,12],'Trigonometric ratios','Angle & coordinates','\\sin^2\\theta+\\cos^2\\theta=1','sine sin cosine cos tangent tan opposite hypotenuse','On the unit circle, the horizontal coordinate is cosine and the vertical coordinate is sine. The right triangle connects coordinates to ratios.','Estimate building height using an angle and a measured distance.','What is sin 30°? Enter a decimal.','0.5'],
['conic','Conic Section 3D Lab','3D Geometry',[11],'Conic sections','A plane through a double cone','x^2+y^2=z^2','ellipse parabola hyperbola circle cutting plane slice','Cutting a double cone with a plane produces a circle, ellipse, parabola or hyperbola, depending on the plane angle and position.','Satellite dishes use parabolic cross sections to focus signals.','How many separate branches does a hyperbola have?','2'],
['matrix','Matrix Transformations','Algebra',[11,12],'Matrices','Linear transformations','\\begin{bmatrix}x^\\prime\\\\y^\\prime\\end{bmatrix}=A\\begin{bmatrix}x\\\\y\\end{bmatrix}','matrix rotation scaling reflection shear determinant','A 2 × 2 matrix transforms each point of a shape. Its columns show where the original basis vectors move.','Computer graphics uses matrices to scale, rotate and reflect shapes.','What is the determinant of the identity matrix?','1'],
['vector','Vector 3D Lab','3D Geometry',[11,12],'Vectors','Direction & magnitude','|\\vec v|=\\sqrt{x^2+y^2+z^2}','vector components dot cross product addition arrow','A vector has a magnitude and a direction. Its components show movement along the three coordinate axes.','Forces and velocities are represented by vectors.','Find the magnitude of vector (3, 4, 0).','5'],
['limit','Limits Visualizer','Calculus',[11,12],'Limits','Approaching a value','\\lim_{x\\to a}x^2=a^2','approach continuity function','A limit describes the value a function approaches as its input approaches a point. The input need not reach the point.','Instantaneous quantities are understood by looking at increasingly small intervals.','Find the limit of x² as x approaches 2.','4'],
['derivative','Secant to Tangent','Calculus',[11,12],'Differentiation','Slope at a point','f^\\prime(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}','derivative secant tangent slope rate differentiability','The secant slope measures average change between two points. As they approach one another, it tends to the tangent slope.','Instantaneous speed is the derivative of distance with respect to time.','Find the derivative of x² at x = 3.','6'],
['integral','Area Under a Curve','Calculus',[12],'Integration','Riemann approximation','\\int_a^b x^2\\,dx=\\frac{b^3-a^3}{3}','integration riemann rectangles area definite integral','Midpoint rectangles approximate the area under a curve. Increasing their number reduces the approximation error.','Integrating a speed graph gives distance travelled.','Find the integral of x² from 0 to 3.','9']
,["decimal","Decimal Hundredths Lab","Numbers",[4,5,6],"Decimals","Tenths and hundredths","d=n/100","decimal hundredths tenths fraction","A hundred equal squares make one whole. Ten hundredths make one tenth.","Prices and metric measurements use decimals.","Write 75 hundredths as a decimal.","0.75"],
["factors","Factors, HCF & LCM","Numbers",[4,5,6,7],"Divisibility","Common factors and multiples","ab=\\operatorname{HCF}(a,b)\\operatorname{LCM}(a,b)","prime composite gcd hcf lcm factor multiple","Factors divide a positive integer with no remainder.","Arrange objects into equal groups or find when repeating schedules meet.","Find HCF of 24 and 36.","12"],
["commercial","Discount & Simple Interest","Commercial Mathematics",[7,8,9],"Money mathematics","Percentages in transactions","I=Prt/100","money rupees discount simple interest price principal","A discount removes a percentage; simple interest adds a fixed percentage of principal each year.","Compare a sale price or calculate simple interest on savings.","Find 20% of 500.","100"],
["quadratic","Quadratic Roots Lab","Algebra",[9,10,11],"Quadratic equations","Discriminant and real roots","x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}","quadratic parabola roots discriminant equation","The graph of ax²+bx+c shows where a quadratic equals zero.","A parabolic trajectory can be modeled with a quadratic.","How many real roots when the discriminant is positive?","2"],
["sequence","Arithmetic Progression Lab","Algebra",[8,9,10,11],"Sequences","Equal differences","a_n=a+(n-1)d","sequence progression arithmetic nth term sum pattern","An arithmetic progression adds the same common difference at every step.","Rows of seats or fixed yearly savings form arithmetic patterns.","Find term 5 when a=2 and d=3.","14"]
];
export const topics:Topic[]=specs.map(([id,title,domain,classes,unit,micro,formula,keywords,learn,real,task,answer])=>({id,title,subtitle:micro,domain,classes,unit,subtopic:unit,micro,formula,keywords:keywords.split(' '),kind:['solid','net','volume','conic','vector'].includes(id)?'3D':'2D',difficulty:classes[0]<=3?'Foundation':classes[0]<=6?'Beginner':classes[0]<=9?'Intermediate':'Advanced',learn,real,task,answer,tabs:['Learn','Explore','Interact','Formula',...(id==='fraction'||id==='pythagoras'?['Proof']:[]),'Experiment','Real life','Practice']}));
for(const [id,g] of Object.entries(labGroups)){const f=formulas.find(f=>f.id===g.formulaIds[0])!;topics.push({id:id as Engine,title:g.title,subtitle:g.story,domain:g.domain,classes:g.classes,unit:g.title,subtopic:g.title,micro:f.title,formula:f.tex,keywords:g.formulaIds.flatMap(id=>{const f=formulas.find(x=>x.id===id);return f?[f.title,f.domain]:[]}),kind:'Interactive',difficulty:f.difficulty,learn:g.story,real:g.story,task:'Change the model inputs and observe the relationship.',answer:'',tabs:['Understand','Explore','Formula','Why','Examples','Real life','Experiment','Practice','Challenge']})}
export const domains=[...new Set(topics.map(t=>t.domain))];
export const boards=['All','CBSE/NCERT','State Board','ICSE'];
export const curriculum={status:'Concept-level guidance; not a verified board syllabus',mappings:Object.fromEntries(boards.slice(1).map(b=>[b,topics.map(t=>({topicId:t.id,classes:t.classes}))]))};
export const navigation=[{label:'Home',mode:'home',icon:'home'},{label:'Learning analytics',mode:'analytics',icon:'chart'},{label:'Explore by class',mode:'classes',icon:'layers'},{label:'Mathematics domains',mode:'domains',icon:'grid'},{label:'Math playground',mode:'playground',icon:'sparkles'},{label:'Formula library',mode:'formulas',icon:'sigma'}];
export const labNavigation=[['Numbers & Patterns','Numbers'],['Arithmetic Workshop','Arithmetic'],['Money & Growth','Commercial Mathematics'],['Coordinate Lab','Coordinate Geometry'],['3D Geometry Lab','3D Geometry'],['Fraction Lab','Fractions'],['Algebra Lab','Algebra'],['Graph Lab','Functions'],['Measurement Lab','Mensuration'],['Geometry Workshop','Geometry'],['Trigonometry Lab','Trigonometry'],['Calculus Lab','Calculus'],['Statistics Lab','Statistics'],['Probability Lab','Probability']];
