import {useRef,useState} from 'react';
import {designPoints,designTiles} from './designStudioMath.mjs';
const templates=[['Rosette','Radial repetition','✺'],['Mosaic','Tile a surface','▦'],['Spiral','Grow & rotate','◎'],['Wave art','Periodic patterns','∿'],['Mandala','Concentric symmetry','❋'],['Math poster','Compose a message','T'],['Blueprint','Plan a layout','⌑'],['Emblem','Design a geometric badge','⬡']];
const palettes=[['Ocean','#244d87','#64c6d4','#f2bd65','#eef6ff'],['Orchid','#6946a5','#d390c9','#f5bf82','#f6f0ff'],['Forest','#206954','#88b98a','#e7bc68','#f0f6ee'],['Sunset','#ad4856','#f59465','#eccb75','#fff4eb']];
export default function DesignStudio(){
 const [template,T]=useState('Rosette'),[palette,P]=useState(0),[count,C]=useState(12),[size,S]=useState(110),[rotation,R]=useState(0),[rings,N]=useState(3),[gap,G]=useState(5),[motif,M]=useState('Petal'),[outline,O]=useState(false),[background,B]=useState('Paper'),[title,H]=useState('Mathematics is beautiful'),[subtitle,U]=useState('Patterns • symmetry • discovery'),[status,F]=useState('');
 const svg=useRef<SVGSVGElement>(null),colors=palettes[palette].slice(1),points=designPoints(count,size,rotation),tiles=designTiles(rings+2,Math.min(16,count),gap);
 const download=()=>{if(!svg.current)return;const url=URL.createObjectURL(new Blob([svg.current.outerHTML],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='visionicx-'+template.toLowerCase().replaceAll(' ','-')+'.svg';a.click();URL.revokeObjectURL(url);F('Your editable SVG design has been exported.');};
 const reset=()=>{C(12);S(110);R(0);N(3);G(5);M('Petal');O(false);B('Paper');H('Mathematics is beautiful');U('Patterns • symmetry • discovery');F('Design controls reset.');};
 function mark(x:number,y:number,index:number,scale=1){const fill=outline?'none':colors[index%3],stroke=colors[index%3],r=Math.max(5,size/5)*scale;return <g key={index} transform={`translate(${x} ${y}) rotate(${rotation+index*360/count})`} fill={fill} stroke={stroke} strokeWidth="2">{motif==='Circle'?<circle r={r}/>:motif==='Square'?<rect x={-r} y={-r} width={2*r} height={2*r}/>:motif==='Triangle'?<polygon points={`0,${-r} ${r},${r} ${-r},${r}`}/>:motif==='Star'?<polygon points={designPoints(10,r,0,0,0).map(([x,y],i)=>`${i%2?x*.45:x},${i%2?y*.45:y}`).join(' ')}/>:motif==='Hexagon'?<polygon points={designPoints(6,r,0,0,0).map(p=>p.join(',')).join(' ')}/>:<ellipse rx={r} ry={r*.4}/>}</g>}
 const explanations:Record<string,string>={Rosette:`${count} equal rotations divide a full turn into ${(360/count).toFixed(2)}° steps. Motifs have evenly spaced centres on a circle; their orientations repeat with the rotation.`,Mosaic:`${rings+2} rows × ${Math.min(16,count)} columns = ${tiles.length} tiles. Gaps are display spacing, not missing units in an area proof.`,Spiral:'Each successive radius increases while the angle advances by a fixed amount. Growth and rotation combine to create an expanding path.', 'Wave art':'Sine gives a repeating vertical displacement. The repetition control changes the number of cycles across the image; size changes amplitude.',Mandala:'Each ring repeats a motif at equal angular intervals. Radial distances change by equal steps; rotate the design to compare the repetition.', 'Math poster':'Use text hierarchy and geometric repetition to communicate an idea. The shapes decorate your message; they do not prove a formula.',Blueprint:'A repeated rectangle layout can represent rooms or blocks. This canvas is a composition preview, not a construction drawing with certified dimensions.',Emblem:'A regular polygon has equally spaced vertices on a circle. The central text and border make a reusable geometric emblem.'};
 return <div className="design-studio"><section className="design-purpose"><span className="eyebrow">WHAT YOU CAN MAKE</span><h3>Mathematical designs you can actually use</h3><div><article><strong>School poster or presentation</strong><p>Choose Math poster, add a title and export SVG artwork that stays sharp on a slide or printed page.</p></article><article><strong>Decoration or geometric emblem</strong><p>Use Rosette, Mandala or Emblem to explore symmetry and make a festival motif, badge or decorative pattern.</p></article><article><strong>A layout to discuss</strong><p>Use Mosaic or Blueprint to compare repetition and spacing. Use the geometry canvas for measured constructions; artwork templates are composition tools.</p></article></div><p><b>Try this:</b> choose Rosette → select Triangle → set 6 repetitions → compare the 60° steps → export your pattern.</p></section><div className="design-template-grid" role="group" aria-label="Design templates">{templates.map(([name,desc,icon])=><button key={name} aria-pressed={template===name} className={template===name?'selected':''} onClick={()=>{T(name);F('')}}><span>{icon}</span><strong>{name}</strong><small>{desc}</small></button>)}</div><div className="design-workspace"><section className="design-preview"><div className="design-preview-heading"><div><span className="eyebrow">LIVE DESIGN</span><h3>{template}</h3></div><button className="primary" onClick={download}>Export SVG ↓</button></div><svg xmlns="http://www.w3.org/2000/svg" ref={svg} viewBox="0 0 720 480" role="img" aria-label={template+' mathematical design'}><rect width="720" height="480" fill={background==='Dark'?'#112139':background==='White'?'#ffffff':colors[3]}/>{background==='Grid'&&<g stroke={colors[0]} opacity=".12">{Array.from({length:25},(_,i)=><path key={i} d={`M${i*30} 0V480M0 ${i*30}H720`}/>)}</g>}
 {template==='Rosette'&&points.map(([x,y],i)=>mark(x,y,i))}
 {template==='Mosaic'&&tiles.map((tile,i)=><g key={i} transform={`translate(${tile.x} ${tile.y})`}>{motif==='Triangle'||motif==='Hexagon'||motif==='Star'?<polygon points={designPoints(motif==='Triangle'?3:motif==='Hexagon'?6:10,tile.size/2,-90,tile.size/2,tile.size/2).map(([x,y],j)=>`${motif==='Star'&&j%2?tile.size/2+(x-tile.size/2)*.45:x},${motif==='Star'&&j%2?tile.size/2+(y-tile.size/2)*.45:y}`).join(' ')} fill={outline?'none':colors[(tile.row+tile.column)%3]} stroke={colors[(tile.row+tile.column)%3]} strokeWidth="2"/>:<rect width={tile.size} height={tile.size} rx={motif==='Circle'?tile.size/2:motif==='Petal'?tile.size/3:0} fill={outline?'none':colors[(tile.row+tile.column)%3]} stroke={colors[(tile.row+tile.column)%3]} strokeWidth="2"/>}</g>)}
 {template==='Spiral'&&Array.from({length:count*rings},(_,i)=>{const angle=(i*27+rotation)*Math.PI/180,r=(i+1)/(count*rings)*Math.min(210,size*1.5);return mark(360+r*Math.cos(angle),240+r*Math.sin(angle),i,.35+i/(count*rings)*.65)})}
 {template==='Wave art'&&Array.from({length:rings},(_,j)=><polyline key={j} points={Array.from({length:301},(_,i)=>`${30+i*2.2},${240+Math.sin(i/300*Math.PI*2*(count/3)+rotation*Math.PI/180+j*.5)*size*.6+(j-(rings-1)/2)*gap*3}`).join(' ')} fill="none" stroke={colors[j%3]} strokeWidth={outline?2:5}/>)}
 {template==='Mandala'&&Array.from({length:rings},(_,j)=>designPoints(count,size*(j+1)/rings,rotation+j*360/count/2).map(([x,y],i)=>mark(x,y,j*count+i,.45+.15*j)))}
 {template==='Math poster'&&<><rect x="35" y="35" width="650" height="410" rx="24" fill="none" stroke={colors[0]} strokeWidth="3"/>{designPoints(count,100,rotation,520,300).map(([x,y],i)=>mark(x,y,i,.8))}<text x="65" y="105" fontSize="28" fill={colors[0]} fontFamily="sans-serif">{title.slice(0,36)}</text><text x="65" y="145" fontSize="15" fill={colors[0]} fontFamily="sans-serif">{subtitle.slice(0,64)}</text><text x="65" y="365" fontSize="22" fill={colors[1]} fontFamily="serif">πr² · a²+b²=c² · y=mx+c</text></>}
 {template==='Blueprint'&&tiles.map((tile,i)=><g key={i}><rect x={tile.x} y={tile.y} width={tile.size} height={tile.size} fill={outline?'none':colors[i%3]+'25'} stroke={colors[0]} strokeWidth="2"/><text x={tile.x+5} y={tile.y+18} fontFamily="sans-serif" fontSize="12" fill={colors[0]}>{tile.row+1}.{tile.column+1}</text></g>)}
 {template==='Emblem'&&<><polygon points={designPoints(Math.max(3,count),size*1.5,rotation).map(p=>p.join(',')).join(' ')} fill={outline?'none':colors[0]+'20'} stroke={colors[0]} strokeWidth="5"/><circle cx="360" cy="240" r={size} fill="none" stroke={colors[1]} strokeWidth="2"/><text x="360" y="245" textAnchor="middle" fontFamily="sans-serif" fontSize="20" fill={colors[0]}>{title.slice(0,24)}</text></>}
 </svg><p>{explanations[template]}</p><p role="status">{status}</p></section><aside className="design-controls"><span className="eyebrow">MAKE IT YOURS</span><h3>1. Choose a look</h3><label>Color palette<select aria-label="Design palette" value={palette} onChange={e=>P(Number(e.target.value))}>{palettes.map(([name],i)=><option key={name} value={i}>{name}</option>)}</select></label><label>Background<select value={background} onChange={e=>B(e.target.value)}>{['Paper','White','Dark','Grid'].map(x=><option key={x}>{x}</option>)}</select></label>{['Rosette','Mandala','Spiral','Mosaic'].includes(template)&&<label>Motif<select value={motif} onChange={e=>M(e.target.value)}>{['Petal','Circle','Square','Triangle','Star','Hexagon'].map(x=><option key={x}>{x}</option>)}</select></label>}<h3>2. Shape the pattern</h3>{[['Repetitions / columns',count,C,3,16],['Design size',size,S,40,140],['Rotation',rotation,R,0,360],['Rings / layers',rings,N,1,5],['Spacing',gap,G,1,12]].filter(([label])=>{const available:Record<string,string[]>={Mosaic:['Repetitions / columns','Rings / layers','Spacing'],Blueprint:['Repetitions / columns','Rings / layers','Spacing'],Rosette:['Repetitions / columns','Design size','Rotation'],Spiral:['Repetitions / columns','Design size','Rotation','Rings / layers'],Mandala:['Repetitions / columns','Design size','Rotation','Rings / layers'],'Wave art':['Repetitions / columns','Design size','Rotation','Rings / layers','Spacing'],'Math poster':['Repetitions / columns','Design size','Rotation'],Emblem:['Repetitions / columns','Design size','Rotation']};return available[template].includes(String(label))}).map(([label,value,set,min,max])=><label key={String(label)}>{String(label)} <strong>{Number(value)}</strong><input type="range" aria-label={String(label)} min={Number(min)} max={Number(max)} value={Number(value)} onChange={e=>(set as (v:number)=>void)(Number(e.target.value))}/></label>)}<label><input type="checkbox" checked={outline} onChange={e=>O(e.target.checked)}/> Outline style</label>{['Math poster','Emblem'].includes(template)&&<><h3>3. Add your message</h3><label>Title<input aria-label="Design title" maxLength={36} value={title} onChange={e=>H(e.target.value)}/></label>{template==='Math poster'&&<label>Subtitle<input maxLength={64} value={subtitle} onChange={e=>U(e.target.value)}/></label>}</>}<button onClick={reset}>Reset design controls</button><p>Select a template → adjust its look → export your design. SVG stays sharp at any size.</p></aside></div></div>
}
