import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,Clock,Download,RotateCcw,Target,Zap} from 'lucide-react';
import {examLessons,practiceSet,scoreExam,correctExamAnswer,practiceVariantsPerLesson,practiceQuestionCount} from './examContent.mjs';
import {createTiming,visitQuestion,recordAnswerTime,finishTiming,durationMs,timeLabel,reportHtml} from './examAttempt.mjs';
import type {ExamCase,ExamLesson,AttemptTiming} from './ExamTypes';
const lessons=examLessons as ExamLesson[];
const tracks=['Arithmetic','Quantitative','Reasoning','Data'];
const lessonMap=Object.fromEntries(lessons.map(l=>[l.id,l]));
const routes:Record<string,string>={Arithmetic:'exam-arithmetic',Quantitative:'exam-quant',Reasoning:'exam-reasoning',Data:'exam-data'};
const presets=[{label:'Learn at your pace',count:10,minutes:0},{label:'Quick sprint',count:5,minutes:5},{label:'Focused test',count:15,minutes:30},{label:'Full practice',count:30,minutes:30}];
export default function ExamPractice(){
 const initialLesson=lessons.find(l=>l.id===new URLSearchParams(location.hash.split('?')[1]||'').get('lesson'));
 const [mode,Mode]=useState(initialLesson?'focused':'random'),[area,Area]=useState(initialLesson?.area||'All'),[topics,Topics]=useState<string[]>(initialLesson?[initialLesson.topic]:[]),[level,Level]=useState('All');
 const [size,Size]=useState(10),[timer,Timer]=useState(false),[minutes,Minutes]=useState(30),[negative,Negative]=useState<boolean|null>(null),[penalty,Penalty]=useState(.25);
 const [questions,Questions]=useState<ExamCase[]>([]),[answers,Answers]=useState<Record<string,string>>({}),[position,Position]=useState(0),[marked,Marked]=useState<string[]>([]);
 const [report,Report]=useState<AttemptTiming|null>(null),[now,Now]=useState(Date.now()),[finishReason,FinishReason]=useState('Submitted by you'),[review,Review]=useState('All'),[sort,Sort]=useState('Question order');
 const timing=useRef<AttemptTiming|null>(null),run=useRef(false),current=useRef(0);
 const selectedPenalty=negative?penalty:0;
 const pool=lessons.filter(l=>mode==='random'||((area==='All'||l.area===area)&&(!topics.length||topics.includes(l.topic))&&(level==='All'||l.level===level)));
 const active=questions.length>0&&!report;
 function begin(next:ExamCase[],useTimer=timer){const start=Date.now();Questions(next);Answers({});Position(0);current.current=0;Marked([]);Report(null);Review('All');Sort('Question order');Now(start);timing.current=createTiming(next.map(q=>q.id),start,useTimer?minutes*60000:0) as AttemptTiming;run.current=true;window.scrollTo({top:0,behavior:'instant'});}
 function startNew(){const next=practiceSet({area:mode==='random'?'All':area,topics:mode==='random'?[]:topics,level:mode==='random'?'All':level,seed:Date.now()%100000000,count:size}) as ExamCase[];if(next.length)begin(next);}
 function submit(reason='Submitted by you'){if(!run.current||!timing.current)return;run.current=false;const end=finishTiming(timing.current,Date.now()) as AttemptTiming;timing.current=end;Report(end);FinishReason(reason);Now(end.endedAt!);window.scrollTo({top:0,behavior:'instant'});}
 useEffect(()=>{if(!active)return;const tick=()=>{const at=Date.now();Now(at);if(timing.current?.deadline&&at>=timing.current.deadline)submit('Time limit reached')};tick();const id=window.setInterval(tick,250);return()=>window.clearInterval(id)},[active]);
 function navigate(index:number){if(!timing.current||!run.current)return;if(timing.current.deadline&&Date.now()>=timing.current.deadline){submit('Time limit reached');return;}timing.current=visitQuestion(timing.current,questions[index].id,Date.now()) as AttemptTiming;current.current=index;Position(index);}
 function select(value:string){if(!timing.current||!run.current)return;if(timing.current.deadline&&Date.now()>=timing.current.deadline){submit('Time limit reached');return;}const q=questions[current.current];timing.current=recordAnswerTime(timing.current,q.id,Date.now()) as AttemptTiming;Answers(a=>({...a,[q.id]:value}));}
 function reset(){run.current=false;timing.current=null;Questions([]);Answers({});Report(null);Marked([]);Position(0);window.scrollTo({top:0,behavior:'instant'});}
 function download(){if(!report)return;const html=reportHtml({questions,answers,timing:report,stats:scoreExam(questions,answers,selectedPenalty),penalty:selectedPenalty,lessonNames:Object.fromEntries(lessons.map(l=>[l.id,l.title])),reportId:String(report.startedAt)});const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='VisionicX-practice-report-'+report.startedAt+'.html';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),60000);}
 const q=questions[position],stats=scoreExam(questions,answers,selectedPenalty),remaining=timing.current?.deadline?Math.max(0,timing.current.deadline-now):0;
 const elapsed=timing.current?Math.max(0,Math.min(now,timing.current.deadline||now)-timing.current.startedAt):0;
 const currentSpent=q&&timing.current?(timing.current.spent[q.id]||0)+Math.max(0,Math.min(now,timing.current.deadline||now)-timing.current.lastAt):0;
 const missed=questions.filter(q=>!correctExamAnswer(answers[q.id],q.answer));
 const filtered=questions.filter(q=>review==='All'||review==='Correct'&&correctExamAnswer(answers[q.id],q.answer)||review==='Incorrect'&&answers[q.id]!==undefined&&!correctExamAnswer(answers[q.id],q.answer)||review==='Skipped'&&answers[q.id]===undefined||review==='Marked'&&marked.includes(q.id));
 const ordered=sort==='Longest time first'&&report?[...filtered].sort((a,b)=>(report.spent[b.id]||0)-(report.spent[a.id]||0)):filtered;
 const resultFor=(q:ExamCase)=>answers[q.id]===undefined?'Skipped':correctExamAnswer(answers[q.id],q.answer)?'Correct':'Incorrect';
 return <section className="exam-practice exam-practice-v2">{!questions.length?<>
  <div className="exam-section-heading"><div><span className="exam-kicker">BUILD YOUR TEST · THREE SIMPLE CHOICES</span><h2>Choose your pace. Start with confidence.</h2></div><Zap size={28}/></div>
  <section className="test-config-section"><div className="config-title"><b>01</b><div><h3>Which questions?</h3><p>Start with a random mix, or choose the topics you want to work on.</p></div></div>
   <div className="test-mode-options"><label className={mode==='random'?'selected':''}><input type="radio" name="question-mode" checked={mode==='random'} onChange={()=>Mode('random')}/><div><strong>Random mixed test</strong><small>From all four tracks · {practiceQuestionCount.toLocaleString()} question variants</small></div></label><label className={mode==='focused'?'selected':''}><input type="radio" name="question-mode" checked={mode==='focused'} onChange={()=>Mode('focused')}/><div><strong>Choose my topics</strong><small>Pick a track, topics and difficulty level</small></div></label></div>
   {mode==='focused'&&<div className="test-focus-options"><div className="exam-setup"><label>Study track<select aria-label="Practice track" value={area} onChange={e=>{Area(e.target.value);Topics([])}}><option>All</option>{tracks.map(t=><option key={t}>{t}</option>)}</select></label><label>Level<select aria-label="Practice level" value={level} onChange={e=>Level(e.target.value)}><option>All</option><option>Foundation</option><option>Intermediate</option><option>Advanced</option></select></label></div><fieldset className="topic-picker"><legend>Choose topics · leave empty for all topics in this track</legend><div>{[...new Set(lessons.filter(l=>area==='All'||l.area===area).map(l=>l.topic))].map(t=><label className={topics.includes(t)?'selected':''} key={t}><input type="checkbox" checked={topics.includes(t)} onChange={()=>Topics(topics.includes(t)?topics.filter(x=>x!==t):[...topics,t])}/>{t}</label>)}</div></fieldset>{topics.length>0&&<button onClick={()=>Topics([])}>Use all topics</button>}</div>}
  </section>
  <section className="test-config-section"><div className="config-title"><b>02</b><div><h3>How long and how many?</h3><p>Choose a ready-made set or adjust the question count and timer.</p></div></div>
   <div className="test-presets">{presets.map(p=><button key={p.label} aria-pressed={size===p.count&&timer===(p.minutes>0)&&(!timer||minutes===p.minutes)} onClick={()=>{Size(p.count);Timer(p.minutes>0);if(p.minutes)Minutes(p.minutes)}}><strong>{p.label}</strong><span>{p.count} questions · {p.minutes?p.minutes+' minutes':'untimed'}</span></button>)}</div>
   <div className="test-time-options"><label>Question count<select aria-label="Practice question count" value={size} onChange={e=>Size(Number(e.target.value))}>{[5,10,15,20,30,50].map(n=><option key={n} value={n}>{n} questions</option>)}</select></label><label className="test-timer-toggle"><input type="checkbox" checked={timer} onChange={e=>Timer(e.target.checked)}/>Use a timer</label>{timer&&<label>Time limit<select aria-label="Practice time limit" value={minutes} onChange={e=>Minutes(Number(e.target.value))}>{[5,10,15,20,30,45,60].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label>}</div>
  </section>
  <section className="test-config-section"><div className="config-title"><b>03</b><div><h3>Do you want negative marking?</h3><p>Correct answers earn +1. Skipped answers earn 0. Choose the rule for incorrect answers.</p></div></div>
   <fieldset className="negative-options"><legend>Negative marking choice</legend><label className={negative===false?'selected':''}><input type="radio" name="negative-marks" checked={negative===false} onChange={()=>Negative(false)}/><div><strong>No negative marks</strong><small>Incorrect answers score 0</small></div></label><label className={negative===true?'selected':''}><input type="radio" name="negative-marks" checked={negative===true} onChange={()=>Negative(true)}/><div><strong>Use negative marks</strong><small>Deduct a penalty for each incorrect answer</small></div></label></fieldset>
   {negative&&<label className="penalty-select">Penalty per incorrect answer<select aria-label="Negative mark penalty" value={penalty} onChange={e=>Penalty(Number(e.target.value))}>{[.25,.33,.5,1].map(n=><option key={n} value={n}>−{n} mark</option>)}</select></label>}
  </section>
  <div className="test-launch"><div><strong>{Math.min(size,pool.length*practiceVariantsPerLesson)} questions · {timer?minutes+' minutes':'no time limit'} · {negative===null?'choose marking above':negative?`+1 / −${penalty}`:'+1 / no penalty'}</strong><p>{pool.length} matching concepts · {(pool.length*practiceVariantsPerLesson).toLocaleString()} available variants. Your set has no repeated questions.</p>{negative===null&&<span>Choose Yes or No for negative marking to start.</span>}</div><button className="exam-primary" disabled={negative===null||!pool.length} onClick={startNew}>{mode==='random'?'Start random test':'Start focused test'}<ArrowRight size={17}/></button></div>
  <p className="exam-note">Worked solutions appear after submission. An attempt stays in this tab and resets if you leave this screen or reload. Parameterized variants change givens within a model; they are not all different question formats.</p>
 </>:report?<div className="exam-report">
  <header className="report-hero"><div><span className="exam-kicker">YOUR ATTEMPT · REVIEW & IMPROVE</span><h2>{stats.correct===questions.length?'A strong finish. Keep the reasoning.':'See your progress. Find your next step.'}</h2><p>{questions.length} questions · {finishReason} · {new Date(report.startedAt).toLocaleDateString('en-IN')}</p><div className="report-score"><strong>{stats.score}<small> / {questions.length}</small></strong><span>Net score after {selectedPenalty?'negative marking':'no-penalty marking'}</span></div></div><div className="report-donut" style={{background:`conic-gradient(#67d7bb ${stats.correct/questions.length*100}%,#e1ab62 0 ${(stats.correct+stats.wrong)/questions.length*100}%,#466079 0)`}}><div><strong>{Math.round(stats.correct/questions.length*100)}%</strong><span>of all questions correct</span></div></div></header>
  <div className="report-metrics">{[[timeLabel(durationMs(report)),'Total exam time'],[stats.accuracy+'%','Accuracy of answered questions'],[`${stats.correct} / ${stats.wrong} / ${stats.skipped}`,'Correct / incorrect / skipped'],[Number((stats.wrong*selectedPenalty).toFixed(3)),'Marks deducted'],[timeLabel(durationMs(report)/questions.length),'Average time per question']].map(([n,label])=><article key={String(label)}><strong>{n}</strong><span>{label}</span></article>)}</div>
  <div className="report-actions"><button className="exam-primary" onClick={()=>begin([...questions])}><RotateCcw size={16}/>Restart this test</button><button onClick={startNew}>New random / focused test</button><button onClick={reset}>Change test settings</button><button onClick={download}><Download size={16}/>Download report</button><button onClick={()=>window.print()}>Print / Save PDF</button><button disabled={!missed.length} onClick={()=>{Timer(false);begin([...missed],false)}}>Retry missed & skipped</button></div>
  <section className="report-section"><div className="exam-section-heading"><div><span className="exam-kicker">YOUR TRACK BREAKDOWN</span><h3>Accuracy and time, side by side</h3></div></div><div className="report-track-grid">{tracks.map(a=>{const qs=questions.filter(q=>lessonMap[q.lessonId].area===a);if(!qs.length)return null;const correct=qs.filter(q=>correctExamAnswer(answers[q.id],q.answer)).length;const time=qs.reduce((sum,q)=>sum+(report.spent[q.id]||0),0);return <article key={a}><strong>{a}</strong><div className="report-track-bar"><span style={{width:correct/qs.length*100+'%'}}/></div><p>{correct} / {qs.length} correct · {timeLabel(time)} spent</p><a href={'#'+routes[a]}>Explore lessons <ArrowUpRight size={13}/></a></article>})}</div></section>
  <section className="report-section"><div className="exam-section-heading"><div><span className="exam-kicker">QUESTION-BY-QUESTION REVIEW</span><h3>Your answers, time and worked solutions</h3></div><span>{ordered.length} questions</span></div><div className="report-review-controls"><label>Show<select aria-label="Report result filter" value={review} onChange={e=>Review(e.target.value)}>{['All','Correct','Incorrect','Skipped','Marked'].map(x=><option key={x}>{x}</option>)}</select></label><label>Sort<select aria-label="Report sort" value={sort} onChange={e=>Sort(e.target.value)}><option>Question order</option><option>Longest time first</option></select></label></div>
   <div className="report-question-list">{ordered.map(q=>{const i=questions.findIndex(x=>x.id===q.id),l=lessonMap[q.lessonId],status=resultFor(q);return <details className={'result-'+status.toLowerCase()} key={q.id}><summary><b>{String(i+1).padStart(2,'0')}</b><div><strong>{l.title}</strong><p>{q.prompt}</p></div><span className="result-badge">{status}</span><span className="question-time"><Clock size={13}/>{timeLabel(report.spent[q.id]||0)}</span><span className="summary-expand">＋</span></summary><div className="report-question-detail"><div className="report-answer-row"><p>Your answer<br/><strong>{answers[q.id]??'Skipped'}</strong></p><p>Correct answer<br/><strong>{q.answer} {q.unit}</strong></p><p>Time on question<br/><strong>{timeLabel(report.spent[q.id]||0)}</strong></p><p>Last answered at<br/><strong>{answers[q.id]!==undefined?timeLabel(report.answeredAt[q.id]||0):'—'}</strong></p></div><h4>Understand the solution</h4><ol className="exam-steps">{q.ways[0].steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p><strong>Watch for:</strong> {l.trap}</p><details className="exam-details"><summary>Compare all five approaches</summary><div className="exam-all-methods">{q.ways.map((w,i)=><article key={w.title}><b>0{i+1}</b><h4>{w.title}</h4><ol>{w.steps.map((s,j)=><li key={j}>{s}</li>)}</ol></article>)}</div></details><a href={'#'+routes[l.area]+'?lesson='+l.id}>Study this concept <ArrowUpRight size={14}/></a></div></details>})}</div>{!ordered.length&&<p>No questions match this review filter.</p>}
  </section><p className="exam-note report-timing-note">Time on a question includes reading, selecting answers and revisits, including time while this tab was in the background. “Last answered at” is elapsed time from test start at the most recent answer selection. Scores measure this attempt; they do not predict a rank or exam readiness.</p>
 </div>:<>
  <div className="exam-session-bar"><div><span className="exam-kicker">ACTIVE TEST · +1 CORRECT / {selectedPenalty?'−'+selectedPenalty+' INCORRECT':'0 INCORRECT'}</span><h2>Question {position+1} of {questions.length}</h2><p>{Object.keys(answers).length} answered · {marked.length} marked for review</p></div><div className="test-live-clocks"><span><Clock size={16}/>{timer?'Remaining':'Elapsed'} <strong>{timeLabel(timer?remaining:elapsed)}</strong></span><span>On this question <strong>{timeLabel(currentSpent)}</strong></span></div><button onClick={()=>submit()} className="exam-primary">Submit test</button></div>
  <div className="exam-session"><aside><h3>Question map</h3><div className="exam-question-map">{questions.map((q,i)=><button key={q.id} aria-label={`Question ${i+1}${answers[q.id]!==undefined?', answered':''}${marked.includes(q.id)?', marked':''}`} aria-current={position===i?'step':undefined} className={`${position===i?'current':''} ${answers[q.id]!==undefined?'answered':''} ${marked.includes(q.id)?'marked':''}`} onClick={()=>navigate(i)}>{i+1}</button>)}</div><p>Filled = answered<br/>Gold border = marked<br/>Ring = current question</p><button onClick={reset}>Discard & return to setup</button></aside><article className="exam-question"><span className="exam-kicker">{lessonMap[q.lessonId].area} · {lessonMap[q.lessonId].title}</span><h3>{q.prompt}</h3><div className="exam-choices">{q.options.map((v,i)=><button key={String(v)} aria-pressed={answers[q.id]===String(v)} className={answers[q.id]===String(v)?'selected':''} onClick={()=>select(String(v))}><b>{'ABCD'[i]}</b>{v} {q.unit}</button>)}</div><div className="exam-actions"><button onClick={()=>Answers(a=>{const next={...a};delete next[q.id];return next})}>Clear answer</button><button aria-pressed={marked.includes(q.id)} onClick={()=>Marked(marked.includes(q.id)?marked.filter(id=>id!==q.id):[...marked,q.id])}>{marked.includes(q.id)?'Unmark':'Mark for review'}</button></div><div className="exam-step-footer"><button disabled={position===0} onClick={()=>navigate(position-1)}>← Previous</button><button className="exam-primary" onClick={()=>position===questions.length-1?submit():navigate(position+1)}>{position===questions.length-1?'Submit test':'Next question →'}</button></div><p className="exam-note">Solutions appear after submission. {timer?'The test submits automatically when time runs out.':'There is no time limit.'} You can revisit and change any answer before submitting.</p></article></div>
 </>}</section>
}
