import {useState} from 'react';
import type {FormulaEntry} from './formulaCatalog';
import {calculate,formatValue} from './formulaMath.mjs';
import {admissible,describeInputs} from './situations';
import {sampleInput} from './formulaSampling';
import {symbolMeaning} from './formulaSymbols';
import {teachingFor} from './formulaTeaching';
import {calculationSteps,readableStep} from './expressionSteps.mjs';
import {Formula} from './components';
export const learningSteps=['See & understand','Build & explore','Predict & discover','Derive & explain','Read the formula','Solve examples','Use in real life','Practice & challenge'];
export function RelationshipExperiment({entry,predict=false,values:external,onValues}:{entry:FormulaEntry;predict?:boolean;values?:Record<string,number>;onValues?:(v:Record<string,number>)=>void}){
 const [local,Local]=useState({...entry.defaults}),[guess,G]=useState(''),[feedback,F]=useState(''),[reveal,R]=useState(!predict);
 const values=external||local,V=onValues||Local;
 const valid=admissible(entry,values),result=valid?calculate(entry.expression,values):NaN;
 const initial=calculate(entry.expression,entry.defaults);
 return <div className="relationship-experiment"><span className="eyebrow">{predict?'PREDICT BEFORE YOU CALCULATE':'BUILD YOUR OWN EXAMPLE'}</span><h3>{predict?'What will this model produce?':'Connect each input to its meaning'}</h3><p>{teachingFor(entry).idea} Start with the example, change one quantity, and compare the output. A pattern from a few examples is evidence to investigate, not a proof.</p><div className="experiment-inputs">{Object.entries(values).map(([key,value])=><label key={key}><strong>{key}</strong><small>{symbolMeaning(key,entry)}</small><input aria-label={'Explore input '+key} type="number" step="any" value={value} onChange={e=>{if(e.target.value==='')return;V({...values,[key]:sampleInput(entry,key,Number(e.target.value))});F('');R(!predict)}}/></label>)}</div><p className="lesson-condition">{entry.condition}</p>{predict&&<label>Your predicted output<input aria-label="Formula prediction" type="number" step="any" value={guess} onChange={e=>{G(e.target.value);F('')}}/></label>}<div className="studio-actions"><button onClick={()=>{V({...entry.defaults});G('');F('');R(!predict)}}>Reset example</button>{predict&&<button className="primary" disabled={!valid} onClick={()=>{R(true);F(guess.trim()&&Math.abs(Number(guess)-result)<=1e-4*Math.max(1,Math.abs(result))?'Your prediction matches. Explain which operations produced it.':'Compare your prediction with the operation trace. Check parentheses, units and the domain.')}}>Test my prediction</button>}</div><p role="status">{feedback}</p>{!valid?<p role="alert">These inputs do not satisfy this model’s conditions. Adjust them before calculating.</p>:reveal&&<><div className="experiment-result"><div><small>Starting output</small><strong>{formatValue(initial)}</strong></div><div><small>Your output · {entry.unit}</small><strong>{formatValue(result)}</strong></div><div><small>Change from start</small><strong>{formatValue(result-initial)}</strong></div></div><ol className="reasoned-steps">{calculationSteps(entry.expression,values).map((s,i)=><li key={i}>{readableStep(s)}</li>)}</ol></>}<p><strong>Visual connection:</strong> use the linked graph above to vary the same input. The graph shows the model’s output, so check whether its shape supports your prediction.</p></div>
}
const specific:Record<string,[string,string][]>={
 'percent-of':[['Convert to a decimal','25% of 80 = 0.25×80 = 20. Percent means per hundred.'],['Fraction shortcut','25%=1/4, so 80÷4=20. This shortcut applies because 25/100 simplifies to 1/4.'],['Build from 10%','For 15% of 240: 10% is 24 and 5% is half of 24, so the total is 36.'],['Swap the percentage','8% of 25 equals 25% of 8, which is 2. Both evaluate to 8×25/100.'],['Reverse the relationship','If 25% of a positive quantity is 20, the whole is 20÷0.25=80. A zero percentage cannot determine a unique whole.']],
 'linear-solve':[['Undo the operations','For 2x+3=11, subtract 3 from both sides, then divide both sides by 2: x=4.'],['Balance model','Removing the same amount from both sides preserves equality; dividing by a nonzero coefficient preserves equality.'],['Graph the crossing','Plot y=2x+3 and y=11. Their intersection has x=4. The graph suggests the solution; substitution verifies it.'],['Substitute the candidate','2×4+3=11, so x=4 satisfies the original equation, not only a rearranged version.'],['Inspect exceptional cases','For ax+b=c, a≠0 gives one solution. If a=0, b=c gives every real x; otherwise there is no solution.']],
 'triangle-area':[['Base times perpendicular height','For b=6,h=4, A=6×4÷2=12 square units. A sloping side is not automatically the height.'],['Double to a parallelogram','Join two congruent triangles to form a parallelogram of area bh. One triangle occupies half the total.'],['Split into right triangles','Drop a perpendicular to split the triangle. Add the two half-rectangle areas; their bases add to b.'],['Reverse for a dimension','If A=12 and b=6, h=2A/b=4. Division requires b>0.'],['Mental strategy','Halve the even factor first: 6×4÷2=3×4=12. This changes arithmetic order without changing the product.']],
 'simple-interest':[['Substitute consistently','P=1000, r=8% annually, t=3 years gives I=1000×8×3/100=240.'],['Find one year first','One year earns 8% of 1000, or 80. Three years at simple interest earn 3×80=240.'],['Decimal-rate method','Convert 8% to 0.08; I=1000×0.08×3=240. Do not divide by 100 again.'],['Reverse for time','For positive P and nonzero rate r, t=100I/(Pr). With I=240,P=1000,r=8, t=3 years.'],['Check the model','Simple interest uses the original principal each period. Compound interest changes the base and requires a different formula.']],
 'compound-amount':[['Growth-factor method','For P=1000,r=10%,n=2, A=1000×1.1²=1210.'],['Year-by-year method','After one year: 1100. After the next: 1100×1.1=1210. Interest now includes the first year’s interest.'],['Expand for two periods','(1+r)²=1+2r+r² with decimal r. The extra r² term distinguishes two-year compounding from simple interest.'],['Reverse the principal','Given A=1210 and two 10% periods, P=1210/1.1²=1000. The growth factor must be nonzero.'],['Estimate and check','Two 10% periods give slightly more than a 20% increase because growth compounds. Use exact powers for the final answer.']],
 'ap-sum':[['Use first and last','For a=2,d=3,n=6, the last term is 17 and S=6×(2+17)/2=57.'],['Pair the endpoints','2+17=5+14=8+11=19. Three pairs total 3×19=57.'],['Use the average term','The mean of an arithmetic progression is (first+last)/2=9.5. Six equally spaced terms sum to 6×9.5=57.'],['Add a constant and increments','The six initial copies contribute 6×2=12; the increments contribute 3×(0+1+2+3+4+5)=45. Total 57.'],['Verify the assumptions','Equal differences are required. Endpoint averaging does not calculate the sum of an arbitrary sequence.']],
 'derivative-square':[['Limit of the difference quotient','((x+h)²−x²)/h=2x+h for h≠0; as h→0, this tends to 2x.'],['Power rule','d(x²)/dx=2x¹=2x; at x=3 the slope is 6.'],['Compare secant slopes','At x=3, h=0.1 gives 6.1, h=−0.1 gives 5.9. Both approach 6; a finite table illustrates, but does not prove, the limit.'],['Read the tangent','The tangent at x=3 touches (3,9) and has slope 6, so y−9=6(x−3).'],['Symmetry and sign check','For x², slope is negative left of zero, zero at zero and positive right of zero. The derivative 2x matches this behavior.']],

 'circle-area':[['Direct substitution','For r=3, A=π×3²=9π square units. Square the radius before multiplying by π.'],['Scale reasoning','Doubling radius multiplies area by 2²=4. Compare radii without recalculating π.'],['Reverse the relationship','For A=25π, divide by π and take the nonnegative square root: r=5.'],['Visual derivation','Rearrange increasingly thin sectors into a strip with base πr and height r.'],['Mental estimate','For r=3, using π≈3 gives area≈27; π≈3.14 gives 28.26. State which precision is required.']],
 'rectangle-area':[['Count an array','A 6×4 rectangle has 4 rows of 6 unit squares, so A=24.'],['Split and add','For 13×7, split 13 into 10+3: 70+21=91. The two strips cover the original rectangle.'],['Reverse division','If area=24 and width=4, length=24÷4=6; width must be positive.'],['Scale reasoning','Scale both sides by k and area grows by k², not k.'],['Mental compensation','For 19×6, calculate 20×6−6=114. Remove the extra one-unit strip.']],
 'product':[['Equal groups','4×6 means four groups of six: 6+6+6+6=24.'],['Distributive split','17×6=(10+7)×6=60+42=102.'],['Compensation','19×6=20×6−6=114.'],['Double and halve','25×16=50×8=100×4=400. Doubling one factor and halving the other preserves the product.'],['Reverse check','If 7×8=56, then 56÷7=8. A zero divisor cannot be used for this check.']],
 'sum':[['Count on','For 8+5, start at 8 and move five steps right to 13.'],['Make ten','8+5=8+2+3=10+3=13.'],['Regroup','27+36=(20+30)+(7+6)=50+13=63.'],['Compensate','49+28=50+28−1=77.'],['Inverse check','If 27+36=63, then 63−36=27.']],
 'pythagoras-hyp':[['Squares then root','Legs 3 and 4 give c²=9+16=25, so c=5.'],['Find a missing leg','If c=13 and a=5, b=√(169−25)=12. Confirm c is the hypotenuse.'],['Recognize a scaled triple','6,8,10 is twice 3,4,5; this saves arithmetic when the sides match the same ratio.'],['Visual area proof','Compare areas of squares on the legs with the square on the hypotenuse using rearranged triangles.'],['Check applicability','A right angle is required. Squaring sides of any triangle without checking the angle is invalid.']],
};
export function SolvingTechniques({entry}:{entry:FormulaEntry}){
 const guide=teachingFor(entry),trace=calculationSteps(entry.expression,entry.defaults),result=calculate(entry.expression,entry.defaults);
 const methods=specific[entry.id]||[
 ['Substitute with meaning',`Identify the requested output and each input’s units. For this example, ${describeInputs(entry.defaults)}. Use ${entry.expression}, giving ${formatValue(result)} ${entry.unit}.`],
 ['Work from the inside out',trace.map(readableStep).join(' Then ')],
 ['Explain the construction',guide.origin.join(' ')],
 ['Compare two cases',`Keep the conditions ${entry.condition} Compare the starting case with a valid changed input in Build & explore. Use the difference to explain the input’s effect; do not assume every formula is proportional.`],
 ['Estimate and verify',`${guide.check} Round inputs only when the question allows approximation. Compare your estimate with ${formatValue(result)} ${entry.unit}; return to exact values for the final calculation.`],
 ];
 return <section className="technique-school"><span className="eyebrow">SOLVE IT MORE THAN ONE WAY</span><h3>Five approaches · choose what fits the question</h3><p>Some approaches calculate the answer; others justify or check it. A shortcut works only when its stated conditions hold.</p><div className="technique-grid">{methods.map(([title,body],i)=><article key={title}><span className="method-number">0{i+1}</span><h4>{title}</h4><p>{body}</p></article>)}</div><div className="confidence-grid"><article><h4>Mental strategies & mathematical tricks</h4><p>{specific[entry.id]?methods.find(([name])=>/Mental|Compens|Make ten|Distributive|scaled triple/i.test(name))?.[1]||methods[1][1]:'Simplify a subexpression first, retain exact fractions or constants until the end, and estimate the scale of the result. Cancellation is valid for common nonzero factors, not for terms joined by addition.'}</p></article><article><h4>Competition foundation</h4><p>Explain why the conditions are necessary. Try a boundary case and a valid counterexample to a tempting claim. Which part of the derivation rules out that claim?</p><details><summary>A claim to investigate</summary><p>“Doubling any one input always doubles the output.” Test it with the interactive model, then inspect {entry.expression}. Powers, offsets, quotients and multiple appearances of a variable can make this false.</p></details></article><article><h4>Build exam confidence</h4><ol><li>Name the quantity asked for.</li><li>List givens and convert units.</li><li>Write the formula and its conditions.</li><li>Show substitution and justified steps.</li><li>State the answer with units and a reasonableness check.</li></ol><p>Practise one question without looking at the solution, then explain a mistake in your own words.</p></article></div></section>
}
