import {sampleInput} from './formulaSampling';
import {useState} from 'react';
import {Line} from '@react-three/drei';
import {StudioCanvas} from './SpatialScenes';
import {calculate,formatValue} from './formulaMath.mjs';
import {admissible} from './situations';
import {inputRange} from './FormulaExplorer';
import type {FormulaEntry} from './formulaCatalog';
export default function FormulaSurface({entry,values,axis}:{entry:FormulaEntry;values:Record<string,number>;axis:string}){const [choice,C]=useState(''),[reset,R]=useState(0);const others=Object.keys(values).filter(k=>k!==axis),second=others.includes(choice)?choice:others[0],xr=inputRange(axis,entry.defaults[axis]),yr=second?inputRange(second,entry.defaults[second]):{min:0,max:1};const rows=Array.from({length:second?17:1},(_,j)=>Array.from({length:61},(_,i)=>{let x=xr.min+(xr.max-xr.min)*i/60,y=yr.min+(yr.max-yr.min)*j/16;x=sampleInput(entry,axis,x);if(second)y=sampleInput(entry,second,y);const inputs={...values,[axis]:x,...(second?{[second]:y}:{})};return {x,y,v:admissible(entry,inputs)?calculate(entry.expression,inputs):NaN}}));const finite=rows.flat().filter(p=>Number.isFinite(p.v)),min=finite.length?Math.min(...finite.map(p=>p.v)):0,max=finite.length?Math.max(...finite.map(p=>p.v)):1,span=max-min||1;return <div className="formula-spatial"><div className="spatial-tools"><strong>Explore the spatial relationship</strong>{second&&<label>Depth input <select aria-label="Spatial depth input" value={second} onChange={e=>C(e.target.value)}>{others.map(k=><option key={k}>{k}</option>)}</select></label>}<button onClick={()=>R(n=>n+1)}>Reset camera ↺</button></div><div className="formula-spatial-stage"><StudioCanvas key={reset} table={false}><group position={[0,-1.7,0]}><gridHelper args={[6,12,'#a4b89d','#d2dccc']}/>{rows.flatMap((row,j)=>{const segments:[number,number,number][][]=[];let points:[number,number,number][]=[];for(const p of row){if(Number.isFinite(p.v)){points.push([-3+(p.x-xr.min)/(xr.max-xr.min)*6,(p.v-min)/span*4,second?-3+(p.y-yr.min)/(yr.max-yr.min)*6:0])}else{if(points.length>1)segments.push(points);points=[]}}if(points.length>1)segments.push(points);return segments.map((pts,k)=><Line key={`${j}-${k}`} points={pts} color={j%2?'#84b9a2':'#2c7961'} lineWidth={2.5}/>)})}<Line points={[[-3,.02,3],[3,.02,3]]} color="#c49448" lineWidth={3}/><Line points={[[-3,0,3],[-3,4,3]]} color="#6686b4" lineWidth={3}/>{second&&<Line points={[[-3,.02,3],[-3,.02,-3]]} color="#916db4" lineWidth={3}/>}</group></StudioCanvas>{!finite.length&&<div className="spatial-empty">No valid samples in this input range. Check the formula conditions or choose another input.</div>}<span className="spatial-orbit-hint">Drag to orbit · Scroll to zoom</span></div><div className="spatial-legend"><span><i style={{background:'#c49448'}}/>{axis}: {formatValue(xr.min)} → {formatValue(xr.max)}</span><span><i style={{background:'#6686b4'}}/>Output: {formatValue(min)} → {formatValue(max)}</span>{second&&<span><i style={{background:'#916db4'}}/>{second}: {formatValue(yr.min)} → {formatValue(yr.max)}</span>}</div><p>{second?`Height is the result as ${axis} and ${second} vary.`:`Output against ${axis}.`} Other inputs stay fixed. Axes are rescaled to fit; gaps represent excluded or undefined samples.</p></div>}
