const factorial=n=>{if(!Number.isInteger(n)||n<0||n>170)return NaN;let r=1;for(let i=2;i<=n;i++)r*=i;return r};
const clean=x=>Math.abs(x)<1e-12?0:x;
const functions={sqrt:Math.sqrt,abs:Math.abs,sin:x=>clean(Math.sin(x)),cos:x=>clean(Math.cos(x)),tan:x=>Math.abs(Math.cos(x))<1e-12?NaN:Math.tan(x),asin:Math.asin,acos:Math.acos,atan:Math.atan,log:Math.log,log10:Math.log10,exp:Math.exp,floor:Math.floor,ceil:Math.ceil,round:Math.round,min:Math.min,max:Math.max,fact:factorial,gcd:(a,b)=>{if(!Number.isInteger(a)||!Number.isInteger(b))return NaN;while(b){[a,b]=[b,a%b]}return Math.abs(a)},choose:(n,r)=>Number.isInteger(n)&&Number.isInteger(r)&&r>=0&&r<=n?factorial(n)/(factorial(r)*factorial(n-r)):NaN};
// A restricted arithmetic parser: no JavaScript evaluation or property access.
export function calculate(expression,values){const tokens=expression.match(/\d*\.?\d+(?:e[+-]?\d+)?|[A-Za-z][A-Za-z0-9]*|[()+\-*/^%,]/g)||[];if(tokens.join('')!==expression.replace(/\s/g,''))return NaN;let i=0;
const atom=()=>{const t=tokens[i++];if(t==='('){const v=sum();if(tokens[i++]!==')')throw Error('parenthesis');return v}if(/^\d|^\./.test(t||''))return Number(t);if(t==='pi')return Math.PI;if(t==='e'&&!Object.hasOwn(values,'e'))return Math.E;if(tokens[i]==='('){i++;const args=[sum()];while(tokens[i]===','){i++;args.push(sum())}if(tokens[i++]!==')'||!functions[t])throw Error('function');return functions[t](...args)}if(!Object.hasOwn(values,t))throw Error('variable');return Number(values[t])};
const power=()=>{const v=atom();if(tokens[i]==='^'){i++;return v**unary()}return v};const unary=()=>{if(tokens[i]==='-'){i++;return -unary()}if(tokens[i]==='+'){i++;return unary()}return power()};const product=()=>{let v=unary();while(['*','/','%'].includes(tokens[i])){const op=tokens[i++],r=unary();v=op==='*'?v*r:op==='/'?r===0?NaN:v/r:v%r}return v};const sum=()=>{let v=product();while(['+','-'].includes(tokens[i])){const op=tokens[i++],r=product();v=op==='+'?v+r:v-r}return v};try{const result=sum();return i===tokens.length&&Number.isFinite(result)?result:NaN}catch{return NaN}}
export const formatValue=x=>Number.isFinite(x)?Math.abs(x)>=1e7||(Math.abs(x)>0&&Math.abs(x)<1e-5)?x.toExponential(4):Number(x.toFixed(5)).toLocaleString('en-IN',{maximumFractionDigits:5}):'Undefined for these inputs';

