type Info=[string,string,string,[string,string,string][],string,string,string];
const row=(q:string,s:string,v:string,vars:string,condition:string,why:string,mistake:string):Info=>[q,s,v,vars.split(';').map(x=>x.split('|') as [string,string,string]),condition,why,mistake];
export const foundations:Record<string,Info>={
number:row('How can you measure distance below zero?','Move along equally spaced positions.','Real numbers have positions on a line with chosen origin and unit scale.','x|position|u;abs(x)|distance from zero|u','The ticks must use equal intervals.','Opposite directions give opposite signs; absolute value records distance without direction.','−5 is smaller than −2 even though its distance from zero is larger.'),
place:row('Why does moving a digit change its value?','Ten small blocks exchange for one larger group.','Each base-ten place is ten times the value of the place to its right.','h|hundreds digit|count;t|tens digit|count;u|ones digit|count;N|represented number|count','This model uses whole numbers 0–999.','Regrouping ten ones as a ten preserves the total number of units.','A digit and its place value are different: 7 in 372 means 70.'),
addition:row('Can you see a sum before counting every object?','Join groups to add; remove a group to subtract.','Addition combines quantities; subtraction finds the difference or the amount remaining.','a|first quantity|count;b|second quantity|count;c|sum or difference|count','This object model uses nonnegative integer quantities.','Every object in either disjoint group is counted once in the sum.','Changing the order preserves addition but generally changes subtraction.'),
array:row('Does rotating a seating plan change its number of seats?','Each row contains the same number of objects.','The product r × c counts r equal rows of c objects.','r|number of rows|count;c|objects per row|count;N|total objects|count','Rows must contain equal numbers of objects.','Repeated addition c + … + c, r times, equals r × c.','Rows and columns are dimensions, not numbers to add.'),
division:row('How do you share fairly when some objects remain?','Fill every group equally; keep the leftovers separate.','For integers N ≥ 0 and d > 0, unique integers q,r satisfy N=dq+r with 0≤r<d.','N|objects to share|count;d|number of groups|count;q|objects per group|count;r|remainder|count','The divisor is positive and the remainder is smaller than it.','q complete rounds use dq objects; the remaining N−dq cannot form another full round.','A remainder as large as the divisor means you can share another complete round.'),
percentage:row('What does 35% actually look like?','Select 35 of 100 equal pieces.','A percentage is a ratio expressed per hundred.','p|percentage|%;p/100|fraction of the whole|no unit','The grid represents one fixed whole divided into equal parts.','Dividing the whole by 100 makes one percent; selecting p parts makes p percent.','The same percentage of different wholes can give different amounts.'),
ratio:row('Can a recipe grow without changing its taste?','Scale both quantities by the same positive factor.','Equivalent ratios have equal quotients when denominators are nonzero.','a|first quantity|count;b|second quantity|count;k|scale factor|no unit','b must be nonzero; compare corresponding quantities in consistent units.','Both the numerator and denominator gain a factor k, which cancels in the quotient.','Adding the same amount to both quantities generally changes a ratio.'),
balance:row('What can you remove while keeping a scale balanced?','Do the same operation on both sides.','An equality remains true when equal quantities are added to or subtracted from both sides.','x|unknown quantity|u;a|known added quantity|u;b|solution shown in this model|u','The right-hand total here is a+b.','Subtracting a from x+a=a+b leaves x=b.','Removing an object from only one side breaks equality.'),
angle:row('How much of a turn opens a door?','An angle records the turn between two rays.','One complete turn is 360 degrees; supplementary angles sum to 180 degrees.','θ|turn angle|degrees;φ|supplement|degrees','A supplement is nonnegative only for angles between 0° and 180°.','Two adjacent angles on a straight line together complete half a turn.','Longer rays do not make a larger angle.'),
coordinate:row('How do two numbers locate one exact point?','First move horizontally, then vertically.','An ordered pair (x,y) specifies signed distances from the axes in a Cartesian plane.','x|horizontal coordinate|u;y|vertical coordinate|u;d|distance from origin|u','The axes are perpendicular and use the same length unit for this distance formula.','The horizontal and vertical displacements form the legs of a right triangle; apply Pythagoras.','(x,y) usually differs from (y,x). Points on an axis belong to no quadrant.'),
graph:row('Can you predict how a line moves before touching a slider?','A rule turns each input into an output.','A function assigns exactly one output to every input in its domain.','x|input|input unit;y|output|output unit;a|slope or scale|depends on family;b|vertical shift|output unit','The displayed family determines how a changes the graph.','For a line, increasing x by one changes y by a, while x=0 gives y=b.','A slope is a rate; the intercept is a starting output.'),
probability:row('Will ten thousand rolls give exactly equal counts?','Run trials and watch relative frequencies settle.','For equally likely finite outcomes, probability is favourable count divided by total count.','P(E)|probability of event|no unit;N|number of trials|count;n(E)|observed favourable trials|count','The coin and die are modeled as fair independent trials.','Many random trials tend to reduce relative fluctuations; equality is not guaranteed for any fixed sample.','A streak does not make the opposite outcome due on the next independent trial.'),
statistics:row('Can one unusual value change the average?','Compare the balance point, middle value and most frequent value.','Mean is sum divided by count; median uses sorted order; modes maximize frequency.','xᵢ|data value|data unit;n|number of observations|count;x̄|mean|data unit;σ²|population variance|data unit squared','Dataset must be nonempty and finite. This lab reports population variance.','Deviations above and below the mean balance: their sum is zero.','Sort before finding the median; a dataset can have multiple modes or no repeated values.'),
trig:row('How does one rotating point encode six ratios?','The unit circle gives cosine horizontally and sine vertically.','For a unit-circle angle θ, sinθ=y and cosθ=x; tanθ=sinθ/cosθ where defined.','θ|angle|degrees;sinθ|vertical coordinate|no unit;cosθ|horizontal coordinate|no unit;tanθ|sinθ divided by cosθ|no unit','Tangent and secant are undefined at cosθ=0; cotangent and cosecant at sinθ=0.','The circle equation x²+y²=1 becomes cos²θ+sin²θ=1.','A right-triangle interpretation uses acute angles; the unit circle extends to every quadrant.'),
solid:row('How can the same object look different from every side?','Rotate a solid and compare its dimensions.','Solids occupy three-dimensional space and have boundary surfaces.','s|cube side|u;r|radius|u;h|perpendicular height|u;V|volume|u³;SA|surface area|u²','Every length uses the same unit; dimensions must be positive.','A cube contains s layers of s² unit squares, giving s³ cubic units.','A perspective drawing changes appearance, not the solid’s dimensions.'),
net:row('Can six flat squares become a box?','Fold connected faces around their hinges.','A net lays out all the faces of a polyhedron in a plane.','s|cube side|u;SA|surface area|u²','This lab shows one valid cube net with six congruent squares.','Each face has area s²; six faces cover the cube’s boundary.','Not every arrangement of six connected squares folds into a cube.'),
matrix:row('What happens when every point follows the same linear rule?','Transform a shape and its coordinate grid together.','A 2×2 matrix maps a vector to a linear combination of its column vectors.','A|transformation matrix|no unit;x,y|original coordinates|u;det A|signed area multiplier|no unit','Only linear transformations fixing the origin are represented here.','Columns show transformed basis vectors; all other points are their linear combinations.','A negative determinant reverses orientation; zero determinant collapses area.'),
vector:row('Can three perpendicular movements make one arrow?','Combine signed components into direction and length.','A Euclidean vector has components in an orthonormal basis and norm √(x²+y²+z²).','x,y,z|signed components|u;norm(v)|magnitude|u','Axes are perpendicular and use the same scale.','Apply Pythagoras first in the xy plane, then include the z component.','Magnitude is nonnegative even when components are negative.'),
conic:row('Why can one cone produce four different curves?','Tilt the plane and watch the intersection change.','Conic sections are curves formed by intersecting a plane with a double cone.','θ|plane tilt to horizontal|degrees;k|nonzero plane offset|u','Cone half-angle is 45°. The finite display clips the infinite curve.','A horizontal plane gives a circle; crossing one cone obliquely gives an ellipse; parallel to a generator gives a parabola; meeting both gives a hyperbola.','The drawn finite ends are clipping boundaries, not endpoints of a parabola or hyperbola.'),
limit:row('Does approaching a point require reaching it?','Move a point closer from either side.','A limit is the output approached as the input approaches a point.','a|approached input|input unit;h|signed separation|input unit;f(a+h)|nearby output|output unit','This lab uses the continuous square function; other functions may fail to have a two-sided limit.','(a+h)²=a²+2ah+h², and both added terms approach zero as h approaches zero.','The value at a point alone does not establish a limit for arbitrary functions.'),
integral:row('How can rectangles estimate a curved region?','Add thin rectangles and reduce their widths.','The definite integral is a limit of signed sums of function heights times interval widths.','a,b|interval bounds|input unit;n|rectangle count|count;Δx|rectangle width|input unit;area|accumulated output|output × input','This lab orders the bounds and uses x²≥0 with midpoint rectangles.','Widths times heights give rectangle areas. Refining the partition makes their sum approach the curved area.','A numerical approximation is not the exact area; this model reports the error.')};

