import {useState} from 'react';
import {useParam} from './parameters';
import Viewport from './Viewport';
import {Circle,Columns3,Grid2X2,MoveHorizontal,Shapes,ArrowRight,Minus,Plus,Lightbulb} from 'lucide-react';
import {motion} from 'framer-motion';
import {Slider,Metric,Stage,Formula,colors} from './components';
import {simplify,fractionCompare,round} from './math.mjs';
const modes=[{name:'Circle',icon:Circle},{name:'Fraction bar',icon:Columns3},{name:'Rectangle',icon:Grid2X2},{name:'Number line',icon:MoveHorizontal},{name:'Objects',icon:Shapes}];
function FractionVisual({n,d,mode,color=colors.green,onSelect}:{n:number;d:number;mode:string;color?:string;onSelect?:(n:number)=>void}){
const wholeCount=Math.max(1,Math.ceil(n/d));
const click=(index:number)=>onSelect?.(index===n?Math.max(0,n-1):index);
if(mode==='Number line')return <Stage label={`${n}/${d} at ${round(n/d)} on the number line`}><line x1="65" y1="220" x2="535" y2="220" stroke="#8ca299" strokeWidth="3"/>{Array.from({length:2*d+1},(_,i)=><g key={i} onClick={()=>onSelect?.(i)} className="svg-click"><line x1={65+i*470/(2*d)} x2={65+i*470/(2*d)} y1="210" y2="230" stroke={colors.ink}/>{i%d===0&&<text x={65+i*470/(2*d)} y="252" textAnchor="middle">{i/d}</text>}</g>)}<motion.circle animate={{cx:65+n/d*235}} cy="220" r="11" fill={color}/><text x={65+n/d*235} y="190" textAnchor="middle" fill={color}>{n}/{d}</text><text x="300" y="320" textAnchor="middle" className="svg-hint">Tap a tick to move the fraction</text></Stage>;
return <div className={`fraction-visual ${wholeCount>1?'multiple':''}`}>{Array.from({length:wholeCount},(_,w)=>{const selected=Math.min(d,Math.max(0,n-w*d));return <svg viewBox="0 0 260 260" key={w} role="img" aria-label={`Whole ${w+1}: ${selected} of ${d} parts selected`}>
{mode==='Circle'?<g>{Array.from({length:d},(_,i)=>{const start=-Math.PI/2+i*2*Math.PI/d,end=start+2*Math.PI/d;const path=d===1?'M 130 20 A 110 110 0 1 1 129.99 20 Z':`M 130 130 L ${130+110*Math.cos(start)} ${130+110*Math.sin(start)} A 110 110 0 ${d===1?1:0} 1 ${130+110*Math.cos(end)} ${130+110*Math.sin(end)} Z`;return <motion.path key={i} d={path} initial={{opacity:0}} animate={{opacity:1,fill:i<selected?color:'#e4ece7'}} transition={{duration:.25,delay:i*.025}} stroke="#f9fbf8" strokeWidth="3" onClick={()=>click(w*d+i+1)} className="svg-click"/>})}<circle cx="130" cy="130" r="11" fill="#fafcf8"/><circle cx="130" cy="130" r="4" fill="#a7bcb2"/></g>:
mode==='Objects'?Array.from({length:d},(_,i)=>{const cols=Math.ceil(Math.sqrt(d));return <g key={i} onClick={()=>click(w*d+i+1)} className="svg-click"><circle cx={30+(i%cols)*200/cols} cy={55+Math.floor(i/cols)*160/Math.ceil(d/cols)} r={Math.min(22,70/cols)} fill={i<selected?color:'#dce6df'}/><text x={30+(i%cols)*200/cols} y={60+Math.floor(i/cols)*160/Math.ceil(d/cols)} textAnchor="middle" fill={i<selected?'white':colors.ink} fontSize="12">{i+1}</text></g>}):
Array.from({length:d},(_,i)=>{const cols=mode==='Fraction bar'?d:(Array.from({length:Math.floor(Math.sqrt(d))},(_,i)=>i+1).filter(v=>d%v===0).pop()||1);const rows=Math.ceil(d/cols);const width=220/cols,height=mode==='Fraction bar'?70:150/rows;return <motion.rect key={i} x={20+i%cols*width} y={(mode==='Fraction bar'?95:55)+Math.floor(i/cols)*height} width={width-3} height={height-3} rx="3" animate={{fill:i<selected?color:'#e4ece7'}} onClick={()=>click(w*d+i+1)} className="svg-click"/>})}
<text x="130" y="248" textAnchor="middle" fill="#7b8c80" fontSize="13">{wholeCount>1?`Whole ${w+1} · `:''}{selected} of {d} equal parts</text></svg>})}</div>;
}
export default function FractionLab({resetKey=0}:{resetKey?:number}){return <FractionEngine key={resetKey}/>}
function FractionEngine(){const [n,setN]=useParam('n',3),[d,setD]=useParam('d',4),[mode,setMode]=useParam('mode','Fraction bar'),[factor,setFactor]=useParam('factor',2),[compare,setCompare]=useParam('compare',false),[cn,setCn]=useParam('cn',2),[cd,setCd]=useParam('cd',3),[labels,setLabels]=useParam('labels',true);const [sn,sd]=simplify(n,d);const val=n/d,relation=fractionCompare(n,d,cn,cd);const mixed=Math.floor(val);return <>
<div className="lab-main fraction-main"><div className="mode-switch">{modes.map(m=><button key={m.name} className={mode===m.name?'selected':''} onClick={()=>setMode(m.name)}><m.icon size={16}/>{m.name}</button>)}</div>
<Viewport><div className="fraction-stage"><div className="stage-tag"><span className="live-dot"/>LIVE VISUALIZATION</div><FractionVisual n={n} d={d} mode={mode} onSelect={setN}/>{labels&&<div className="fraction-caption"><div className="big-fraction"><span>{n}</span><span>{d}</span></div><div><strong>{n===0?'No parts selected':n===d?'One complete whole':n>d?'More than one whole':'Parts of a whole'}</strong><p>{n} selected · {d} equal parts in each whole</p></div></div>}<div className="stage-note">Click a part to change the numerator. Try the sliders to repartition the whole.</div></div></Viewport>
<div className="conversion-strip" data-testid="fraction-measurements"><Metric label="FRACTION" value={`${n} / ${d}`}/><span>=</span><Metric label="DECIMAL" value={round(val,4)}/><span>=</span><Metric label="PERCENTAGE" value={`${round(val*100,2)}%`}/><span>=</span><Metric label="SIMPLIFIED" value={`${sn} / ${sd}`}/></div>
<div className="insight"><Lightbulb size={21}/><p><strong>Same whole. Different perspective.</strong> Every view represents the same quantity. Change the model and watch the fraction stay connected.</p></div>
{compare&&<div className="comparison"><h3>Compare two fractions</h3><div className="comparison-visual"><div><FractionVisual n={n} d={d} mode={mode}/><strong>{n}/{d}</strong></div><b>{relation<0?'＜':relation>0?'＞':'＝'}</b><div><FractionVisual n={cn} d={cd} mode={mode} color={colors.orange}/><strong>{cn}/{cd}</strong></div></div><p>Cross products: {n} × {cd} = {n*cd} and {cn} × {d} = {cn*d}.</p></div>}
</div><aside className="controls"><div className="controls-heading"><h3>Make it yours</h3><span>01</span></div><p className="muted">One small change. A new discovery.</p><div className="stepper"><span>Numerator <small>Parts you select</small></span><div><button aria-label="Decrease numerator" disabled={n===0} onClick={()=>setN(n-1)}><Minus size={14}/></button><strong>{n}</strong><button aria-label="Increase numerator" disabled={n===2*d} onClick={()=>setN(n+1)}><Plus size={14}/></button></div></div><Slider label="Numerator" value={n} max={2*d} onChange={setN}/><Slider label="Denominator" value={d} min={1} max={12} onChange={v=>{setD(v);setN(Math.min(n,2*v))}}/>
<div className="control-divider"/><h4>Equivalent fractions</h4><SpatialFractionControls/><p className="muted">Multiply both parts by the same number.</p><Slider label="Scale factor" value={factor} min={1} max={6} onChange={setFactor}/><div className="equivalent"><span>{n}/{d}</span><ArrowRight size={17}/><strong>{n*factor}/{d*factor}</strong></div><div className="mini-partition">{Array.from({length:d*factor},(_,i)=><i key={i} style={{background:i<n*factor?colors.green:'#e4ece7'}}/>)}</div><small className="muted">{n*factor} selected from {d*factor} equal parts</small>
<div className="control-divider"/><label className="toggle-row"><span>Comparison mode</span><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/></label>{compare&&<><Slider label="Second numerator" value={cn} max={2*cd} onChange={setCn}/><Slider label="Second denominator" value={cd} min={1} onChange={v=>{setCd(v);setCn(Math.min(cn,v*2))}}/></>}<label className="toggle-row"><span>Show labels</span><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/></label><div className="control-divider"/><div className="control-tip"><small>WHAT YOU’RE SEEING</small><p>{n<d?'A proper fraction is less than one whole.':n===d?'When numerator and denominator match, the value is one.':`An improper fraction: ${mixed} whole${mixed>1?'s':''}${n%d?` and ${n%d}/${d}`:''}.`}</p><Formula tex={`\\frac{${n}}{${d}}=${round(val,4)}`}/></div></aside></>}


function SpatialFractionControls(){const [explode,E]=useParam('explode',0),[subdivide,S]=useParam('subdivide',false);return <><Slider label="Separate pizza pieces" value={explode} onChange={E} min={0} max={.5} step={.05}/><label className="toggle-row">Subdivide the 3D pizza<input type="checkbox" checked={subdivide} onChange={e=>S(e.target.checked)}/></label></>}
