export const legacyCases=[
['quotient','Classroom supplies','Divide 24 pencils equally among 6 learners.','pencils per learner',{a:24,b:6}],
['product','Orchard planting','Plant 6 rows with 8 trees in each row.','trees',{a:6,b:8}],
['remainder','Packing lunch boxes','Pack 29 apples in boxes of 6. How many remain?','apples',{a:29,b:6}],
['sum','Library shelves','Combine 125 fiction books and 83 science books.','books',{a:125,b:83}],
['difference','Bus seats','A bus has 48 seats and 31 passengers. How many seats are free?','seats',{a:48,b:31}],
['fraction-percent','Attendance','18 of 24 students attended. What percentage attended?','%',{n:18,d:24}],
['ratio-share','Team budget','Share ₹900 in a 2:3 ratio. Find the first share.','₹',{T:900,a:2,b:3}],
['scale-length','Map distance','A map uses 50 km per cm. Find the distance for 4 cm.','km',{k:50,s:4}],
['percent-of','Recipe ingredients','A 400 g mixture contains 25% oats. Find the oat mass.','g',{Q:400,p:25}],
['percent-increase','Club membership','A club of 200 members grows by 15%. Find its new size.','members',{P:200,r:15}],
['percent-decrease','Reducing water use','Reduce 250 litres of daily use by 20%. Find the new use.','litres',{P:250,r:20}],
['percent-change','Harvest comparison','A harvest grows from 80 kg to 100 kg. Find percentage growth.','%',{O:80,N:100}],
['profit','School fundraiser','Buy materials for ₹500 and sell the crafts for ₹650. Find the profit.','₹',{CP:500,SP:650}],
['profit-rate','Market stall','Cost is ₹400 and selling price is ₹500. Find profit as a percentage of cost.','%',{CP:400,SP:500}],
['sale-price','Bookshop offer','A ₹800 book has a 25% discount. Find the sale price.','₹',{MP:800,d:25}],
['discount-amount','Sports shop savings','A ₹1200 item has a 15% discount. Find the amount saved.','₹',{MP:1200,d:15}],
['tax-inclusive','Illustrative receipt','Add an illustrative 10% tax to a ₹500 base price. Find the total.','₹',{P:500,r:10}],
['simple-interest','Savings model','₹2000 earns simple interest at 5% annually for 3 years. Find interest earned.','₹',{P:2000,r:5,t:3}],
['compound-amount','Compound growth model','₹1000 grows at 8% annually for 3 complete years. Find the final amount.','₹',{P:1000,r:8,n:3}],
['rectangle-area','Garden bed','A garden is 6 m long and 4 m wide. Find its area.','m²',{l:6,w:4}],
['rectangle-perimeter','Garden fencing','Fence a 12 m by 8 m rectangle with no openings. Find fence length.','m',{l:12,w:8}],
['triangle-area','Sail fabric','A triangular sail has a 6 m base and perpendicular height 4 m. Find fabric area.','m²',{b:6,h:4}],
['trapezium-area','Land survey','Parallel boundaries measure 4 m and 8 m, separated by 3 m. Find area.','m²',{a:4,b:8,h:3}],
['circle-area','Circular lawn','A circular lawn has radius 3 m. Find its area.','m²',{r:3}],
['semicircle-area','Window design','A semicircular window has radius 2 m. Find its glass area.','m²',{r:2}],
['cylinder-volume','Water tank','A cylindrical tank has radius 2 m and height 3 m. Find capacity in cubic metres.','m³',{r:2,h:3}],
['cone-volume','Grain storage','Model grain as a cone of radius 2 m and height 3 m. Find volume.','m³',{r:2,h:3}],
['sphere-volume','Balloon model','A spherical balloon has radius 3 cm. Find enclosed volume.','cm³',{r:3}],
['similar-area','Enlarging a mural','A 6 m² design is enlarged by a linear factor of 2. Find new area.','m²',{A:6,k:2}],
['similar-volume','Scale-model sculpture','An 8 cm³ model is enlarged by a linear factor of 2. Find new volume.','cm³',{V:8,k:2}],
['point-distance','Robot navigation','A robot travels straight from (1,2) to (4,6), with coordinates in metres. Find distance.','m',{x1:1,y1:2,x2:4,y2:6}],
['height-distance','Building survey','Stand 20 m from a building; its top is at 30° elevation. Find height above eye level.','m',{d:20,theta:30}],
['motion-position','Moving trolley','A trolley starts at 3 m/s and accelerates at 2 m/s² for 4 seconds. Find displacement.','m',{u:3,a:2,t:4}],
['motion-velocity','Velocity model','Initial velocity is 3 m/s and acceleration is 2 m/s² for 4 seconds. Find final velocity.','m/s',{u:3,a:2,t:4}],
['weighted-mean','Combining batches','Two equal-scale measurements are 4 and 8 with weights 2 and 3. Find their weighted mean.','units',{w1:2,x1:4,w2:3,x2:8}],
['probability-classical','Fair die','Three of six equally likely faces are even. Find the chance of an even result.','probability',{f:3,N:6}],
['probability-independent','Two fair coins','Each coin has head probability 0.5. Find the chance of two heads.','probability',{p:.5,q:.5}],
['experimental-frequency','Quality sample','47 of 100 test items passed. Find the observed pass fraction.','relative frequency',{n:47,N:100}],
['binomial-mean','Seed germination model','20 independent seeds each have germination probability 0.3. Find the expected germinated count.','seeds',{n:20,p:.3}],
['vector-magnitude','Drone displacement','A drone moves 3 m east, 4 m north and 2 m upward. Find straight-line displacement.','m',{x:3,y:4,z:2}]
] as const;
