export const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
export const simplify=(n,d)=>{const g=gcd(n,d);return [n/g,d/g]};
export const round=(x,d=3)=>Number(x.toFixed(d));
export const fractionCompare=(a,b,c,d)=>Math.sign(a*d-c*b);
export const statistics=values=>{const sorted=[...values].sort((a,b)=>a-b), n=sorted.length;if(!n)return null;const mean=values.reduce((a,b)=>a+b,0)/n; const median=n%2?sorted[(n-1)/2]:(sorted[n/2-1]+sorted[n/2])/2;const freq=new Map();values.forEach(v=>freq.set(v,(freq.get(v)||0)+1));const max=Math.max(...freq.values());const mode=max===1?[]:[...freq].filter(([,f])=>f===max).map(([v])=>v);const variance=values.reduce((s,v)=>s+(v-mean)**2,0)/n;return {mean,median,mode,range:sorted[n-1]-sorted[0],variance,sd:Math.sqrt(variance)}};
export const triangleMetrics=points=>{const [a,b,c]=points;const distance=(p,q)=>Math.hypot(p[0]-q[0],p[1]-q[1]);const sides=[distance(b,c),distance(a,c),distance(a,b)];const area=Math.abs((b[0]-a[0])*(c[1]-a[1])-(c[0]-a[0])*(b[1]-a[1]))/2;const angles=sides.map((s,i)=>{const t=sides[(i+1)%3],u=sides[(i+2)%3];return Math.acos(Math.max(-1,Math.min(1,(t*t+u*u-s*s)/(2*t*u))))*180/Math.PI});return {sides,area,perimeter:sides.reduce((a,b)=>a+b,0),angles}};
export const riemann=(a,b,n)=>{const dx=(b-a)/n;let sum=0;for(let i=0;i<n;i++)sum+=(a+(i+.5)*dx)**2*dx;return sum};

export const triangleCenters=points=>{const [a,b,c]=points,m=triangleMetrics(points),centroid=[(a[0]+b[0]+c[0])/3,(a[1]+b[1]+c[1])/3],perimeter=m.perimeter;if(m.area<1e-8||!Number.isFinite(perimeter))return {centroid,incenter:null,circumcenter:null,orthocenter:null,inradius:0,circumradius:0};const incenter=[0,1].map(i=>(m.sides[0]*a[i]+m.sides[1]*b[i]+m.sides[2]*c[i])/perimeter),den=2*(a[0]*(b[1]-c[1])+b[0]*(c[1]-a[1])+c[0]*(a[1]-b[1])),aa=a[0]**2+a[1]**2,bb=b[0]**2+b[1]**2,cc=c[0]**2+c[1]**2;const circumcenter=[(aa*(b[1]-c[1])+bb*(c[1]-a[1])+cc*(a[1]-b[1]))/den,(aa*(c[0]-b[0])+bb*(a[0]-c[0])+cc*(b[0]-a[0]))/den];return {centroid,incenter,circumcenter,orthocenter:[3*centroid[0]-2*circumcenter[0],3*centroid[1]-2*circumcenter[1]],inradius:2*m.area/perimeter,circumradius:Math.hypot(circumcenter[0]-a[0],circumcenter[1]-a[1])}};
