import {teachingFor} from './formulaTeaching';
import {calculationSteps,readableStep} from './expressionSteps.mjs';
import {labGroups} from './labGroups';
import {formulas} from './formulaCatalog';
import {calculate,formatValue} from './formulaMath.mjs';
import {alternativeFor,describeInputs} from './situations';
import type {Topic} from './data';
import type {LearningPack} from './learning';
export function newLabLearning(t:Topic):LearningPack|null{const group=labGroups[t.id];if(!group)return null;const entries=group.formulaIds.map(id=>formulas.find(f=>f.id===id)!),first=entries[0];let last={...first.defaults};const examples=Array.from({length:4},(_,i)=>{const f=entries[i%entries.length];const values=entries.length===1?(i===0?last:alternativeFor({...f,defaults:last})):f.defaults;last=values;const result=calculate(f.expression,values);return {label:['Start here','Change the input','Compare the model','Explain the relationship'][i],question:`${f.title}: find the result for ${describeInputs(values)}.`,steps:[`Choose ${f.title.toLowerCase()}. ${f.condition}`,`Substitute ${describeInputs(values)}.`,...calculationSteps(f.expression,values).map(readableStep),`Computed result: ${formatValue(result)} ${f.unit}.`,teachingFor(f).check],params:{...values,formulaId:f.id}}});const values=alternativeFor(first),target={...values,formulaId:first.id},changes=Object.keys(values).filter(k=>values[k]!==first.defaults[k]),changeText=changes.map(k=>`${k} from ${first.defaults[k]} to ${values[k]}`).join(' and ')||'the displayed inputs',result=calculate(first.expression,values),before=calculate(first.expression,first.defaults),delta=Math.max(1,Math.abs(result)*.2);return {curiosity:`What changes when you vary the inputs in ${first.title.toLowerCase()}?`,simple:teachingFor(first).idea+' '+group.story,formal:`${first.title} uses the relationship displayed below. ${first.condition}`,read:`Match each symbol to its input, substitute the values, and read the output in ${first.unit}.`,variables:Object.keys(first.defaults).map(k=>[k,`parameter ${k} in ${first.title}`,'see formula condition and input label']),condition:first.condition,why:teachingFor(first).origin.join(' '),mistake:'A plotted model is sampled within its valid domain; it is not a proof. Check conditions and consistent units before interpreting the result.',experiment:{question:`Predict the result when you change ${changeText}. Other inputs stay at their starting values.`,choices:[formatValue(result),formatValue(result+delta),formatValue(result-delta)],correct:0,before:{...first.defaults,formulaId:first.id},after:target,explain:`The starting output is ${formatValue(before)} ${first.unit}. The changed inputs give ${formatValue(result)} ${first.unit}. ${changes.length>1?'These inputs change together to preserve the model conditions.':''}`},examples,practice:{prompt:`Select ${first.title}. Recreate these inputs: ${describeInputs(values)}.`,target,keys:Object.keys(target),hint:'Use the labeled inputs. Check the condition before reading the result.'},challenge:{prompt:examples[3].question+' Recreate the model and explain the output.',target:examples[3].params,keys:Object.keys(examples[3].params),hint:'Compare the final worked example with the graph and condition.'},prerequisites:t.domain==='Calculus'?['graph']:t.domain==='Geometry'?['angle']:['number'],next:t.domain==='Calculus'?['integral']:['graph']}}
