import {createContext,useContext,useState,useCallback,useEffect,type ReactNode,type Dispatch,type SetStateAction} from 'react';
import {labGroups} from './labGroups';
import {formulas} from './formulaCatalog';
import {conceptsFor} from './concepts';
import type {Topic} from './data';
export type Parameters=Record<string,unknown>;
export type ViewMode='2D'|'3D'|'Split';
export function initialParameters(id:string):Parameters{const base={a:4,b:3,n:12,shape:id==='volume'?'Cylinder':'Cube',r:1.4,h:2.5,x:2,y:2,z:1,angle:20,offset:.7,unfold:false,transparent:id==='volume',auto:false,labels:true,axes:true,fill:.5,explode:0,operation:'Add',removed:false,proof:false,points:[[100,290],[450,290],[260,70]],func:'Linear',transform:'Scale',text:'4, 7, 3, 9, 5, 7, 8, 6',outcomes:[0,0,0,0,0,0],experiment:'Die',trials:0};const group=labGroups[id];if(group){const f=formulas.find(f=>f.id===group.formulaIds[0])!;return {...base,...f.defaults,formulaId:f.id}}return {...base,...({fraction:{n:3,d:4,factor:2,cn:2,cd:3,compare:false,mode:'Fraction bar'},number:{a:3},place:{a:237},addition:{a:3,b:2},array:{a:4,b:5},division:{a:17,b:5},percentage:{a:35},ratio:{a:2,b:3},balance:{a:3,b:4},angle:{a:60},trig:{a:35},graph:{a:1,b:0},coordinate:{a:1,b:0},matrix:{a:1,b:1},limit:{a:1,b:1},derivative:{a:2,b:1,func:'Square',playing:false},integral:{a:0,b:3},pythagoras:{a:3,b:4,proofStep:0},commercial:{a:500,b:20,rate:8,time:3,mode:'Discount'},factors:{a:24,b:36},quadratic:{a:1,b:-3,c:2},sequence:{a:2,b:3,n:6},decimal:{a:75,b:100}} as Record<string,Parameters>)[id]}}
type Context={topic:Topic;values:Parameters;setValues:Dispatch<SetStateAction<Parameters>>;set:(p:Parameters)=>void;view:ViewMode;setView:(v:ViewMode)=>void;section:string;setSection:(s:string)=>void};
const ParameterContext=createContext<Context|null>(null);
export function ParameterProvider({topic,children,initialSection='Explore'}:{topic:Topic;children:ReactNode;initialSection?:string}){const [values,setValues]=useState(()=>{const id=new URLSearchParams(location.hash.split('?')[1]||'').get('concept'),c=conceptsFor(topic.id).find(c=>c.id===id);return {...initialParameters(topic.id),...c?.preset}}),[view,setView]=useState<ViewMode>('Split'),[section,setSection]=useState(initialSection);useEffect(()=>setSection(initialSection),[initialSection]);return <ParameterContext.Provider value={{topic,values,setValues,set:p=>setValues(old=>({...old,...p})),view,setView,section,setSection}}>{children}</ParameterContext.Provider>}
export function useLab(){const c=useContext(ParameterContext);if(!c)throw new Error('A mathematics engine needs a ParameterProvider');return c}
export function useParam<T>(key:string,fallback:T):[T,Dispatch<SetStateAction<T>>]{const c=useLab();const setter=useCallback<Dispatch<SetStateAction<T>>>(value=>c.setValues(old=>({...old,[key]:typeof value==='function'?(value as (v:T)=>T)((old[key]===undefined?fallback:old[key]) as T):value})),[key,c.setValues]);return [(c.values[key]===undefined?fallback:c.values[key]) as T,setter]}
