import {useEffect,useState,type PointerEvent} from 'react';
import {motion} from 'framer-motion';
import {Shell} from './Labs';
import {Stage,Slider,Formula,colors} from './components';
import {useLab,useParam} from './parameters';
import {round} from './math.mjs';
const G=colors.green,O=colors.orange,B=colors.blue;
export const positionAt=(x:number,kind:string)=>kind==='Cubic'?x**3/3:kind==='Sine'?Math.sin(x):x*x;
export const derivativeAt=(x:number,kind:string)=>kind==='Cubic'?x*x:kind==='Sine'?Math.cos(x):2*x;
export function PythagorasLab(){const {topic,set}=useLab(),[a,A]=useParam('a',3),[b,BSet]=useParam('b',4),[step,S]=useParam('proofStep',0),[playing,P]=useState(false),[drag,D]=useState<string|null>(null);const c=Math.hypot(a,b),scale=250/(a+b+Math.max(a,b)),px=(x:number)=>260+x*scale,py=(y:number)=>220-y*scale;
useEffect(()=>{if(!playing)return;const timer=setInterval(()=>S(old=>{if(old>=3){P(false);return old}return old+1}),1800);return()=>clearInterval(timer)},[playing,S]);
const change=(e:PointerEvent<SVGSVGElement>)=>{if(!drag)return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)*600/rect.width,y=(e.clientY-rect.top)*400/rect.height;if(drag==='a')A(round(Math.max(1,Math.min(20,(x-260)/scale)),1));else BSet(round(Math.max(1,Math.min(20,(220-y)/scale)),1))};
const square=(pts:number[][],color:string)=><polygon points={pts.map(([x,y])=>`${px(x)},${py(y)}`).join(' ')} fill={color} fillOpacity=".26" stroke={color} strokeWidth="2"/>;
return <Shell note={step?'The outer square and the four triangle areas stay the same. Compare what is left uncovered.':'Drag either handle; the legs stay perpendicular. Every square has a side equal to its matching triangle side.'} metrics={[["a²",`${round(a*a,2)} u²`],["b²",`${round(b*b,2)} u²`],["c²",`${round(c*c,2)} u²`]]} controls={<><Slider label="Leg a" value={a} onChange={A} min={1} max={20} step={.1}/><Slider label="Leg b" value={b} onChange={BSet} min={1} max={20} step={.1}/><Formula tex={`${round(a*a,2)}+${round(b*b,2)}=${round(c*c,2)}`}/><div className="control-divider"/><h4>Move the proof, one step at a time</h4><div className="button-row"><button onClick={()=>S(Math.max(0,step-1))} disabled={step===0}>Back</button><button onClick={()=>S(Math.min(3,step+1))} disabled={step===3}>Next step</button></div><button className="primary" onClick={()=>{if(!playing&&step===3)S(0);P(!playing)}}>{playing?'Pause demonstration':'Demonstrate the proof'}</button><button className="secondary" onClick={()=>{P(false);S(0)}}>Reset proof</button><p className="muted" style={{marginTop:12}}>Step {step}/3 · {['Build the right triangle','Make a square around four triangles','Rearrange the same triangles','Compare equal uncovered areas'][step]}</p><button className="secondary" onClick={()=>set({a:5,b:12})}>Try a 5–12–13 triangle</button></>}>
{step===0?<svg viewBox="0 0 600 400" className="svg-stage" role="img" aria-label="Right triangle with squares on each side. Drag the leg handles." onPointerMove={change} onPointerUp={()=>D(null)} onPointerCancel={()=>D(null)}>
{square([[0,0],[a,0],[a,-a],[0,-a]],G)}{square([[0,0],[0,b],[-b,b],[-b,0]],O)}{square([[a,0],[0,b],[b,a+b],[a+b,a]],B)}<polygon points={`${px(0)},${py(0)} ${px(a)},${py(0)} ${px(0)},${py(b)}`} fill="#faf8ec" stroke={G} strokeWidth="2"/><path d={`M${px(.3)} ${py(0)}V${py(.3)}H${px(0)}`} stroke={G} fill="none"/>{[['a',a,0],['b',0,b]].map(([id,x,y])=><circle key={String(id)} cx={px(Number(x))} cy={py(Number(y))} r="9" fill={id==='a'?G:O} className="svg-click" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);D(String(id))}}/>)}<text x={px(a/2)} y={py(-a/2)} textAnchor="middle">a² = {round(a*a,2)}</text><text x={px(-b/2)} y={py(b/2)} textAnchor="middle">b² = {round(b*b,2)}</text><text x={px((a+b)/2)} y={py((a+b)/2)} textAnchor="middle">c² = {round(c*c,2)}</text><text x="300" y="385" textAnchor="middle">a = {a} · b = {b} · c ≈ {round(c,3)}</text></svg>:<Rearrangement a={a} b={b} step={step}/>}
</Shell>}
function Rearrangement({a,b,step}:{a:number;b:number;step:number}){const scale=250/(a+b),aa=a*scale,bb=b*scale,L=aa+bb,x=180,y=55;const before=[[[0,0],[aa,0],[0,bb]],[[aa,0],[L,0],[L,aa]],[[L,aa],[L,L],[bb,L]],[[0,bb],[bb,L],[0,L]]];const after=[[[aa,0],[L,0],[L,aa]],[[aa,0],[aa,aa],[L,aa]],[[0,aa],[aa,aa],[aa,L]],[[0,aa],[0,L],[aa,L]]];const points=step>=2?after:before;return <Stage label="Four identical right triangles rearrange inside a square"><rect x={x} y={y} width={L} height={L} fill="#e4ecdb" stroke={G} strokeWidth="2"/>{points.map((pts,i)=><motion.polygon key={i} initial={false} points={before[i].map(p=>`${x+p[0]},${y+p[1]}`).join(' ')} animate={{points:pts.map(p=>`${x+p[0]},${y+p[1]}`).join(' ')}} transition={{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:1.1,ease:'easeInOut'}} fill={O} stroke="#fafaf4" strokeWidth="2"/>)}{step===1?<text x={x+L/2} y={y+L/2} textAnchor="middle">c² = {round(a*a+b*b,2)}</text>:<><text x={x+aa/2} y={y+aa/2} textAnchor="middle">a² = {round(a*a,2)}</text><text x={x+aa+bb/2} y={y+aa+bb/2} textAnchor="middle">b² = {round(b*b,2)}</text></>}<text x="300" y="350" textAnchor="middle">{step===3?'Same outer square − same four triangles → a² + b² = c²':'Outer square side: a + b. Each orange triangle: ab/2.'}</text></Stage>}
export function DerivativeLab(){const {set}=useLab(),[a,A]=useParam('a',2),[h,H]=useParam('b',1),[kind,K]=useParam('func','Square'),[playing,P]=useParam('playing',false),[drag,D]=useState<'a'|'h'|null>(null);const f=(x:number)=>positionAt(x,kind),tan=derivativeAt(a,kind),sec=h===0?tan:(f(a+h)-f(a))/h;const xScale=260/Math.max(5,Math.abs(a+h)+.5),yScale=230/Math.max(9,Math.abs(f(a)),Math.abs(f(a+h)));const sx=(x:number)=>300+x*xScale,sy=(y:number)=>280-y*yScale;
useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{H(old=>{if(Math.abs(old)<.005){P(false);return 0}return round(old*.85,5)})},120);return()=>clearInterval(timer)},[playing,H,P]);
const move=(e:PointerEvent<SVGSVGElement>)=>{if(!drag)return;const r=e.currentTarget.getBoundingClientRect(),x=((e.clientX-r.left)*600/r.width-300)/xScale;if(drag==='a')A(round(Math.max(-3,Math.min(4,x)),2));else H(round(Math.max(-2,Math.min(2,x-a)),2))};const curve=Array.from({length:201},(_,i)=>{const x=-5+i*.05;return `${i?'L':'M'}${sx(x)} ${sy(f(x))}`}).join(' ');const line=(m:number)=>`M${sx(-5)} ${sy(f(a)+m*(-5-a))}L${sx(5)} ${sy(f(a)+m*(5-a))}`;
return <Shell note={h===0?'At zero separation the quotient is undefined. The blue line shows the independently computed limiting tangent.':'The green car marks the first position. The gold car marks the later position. Their average signed rate is the orange secant slope. The track rescales to keep both positions visible.'} metrics={[["Δt",`${round(h,4)} s`],["Average rate",h===0?'undefined':`${round(sec,4)} m/s`],["Instantaneous rate",`${round(tan,4)} m/s`]]} controls={<><label className="control-select">Position model<select aria-label="Position model" value={kind} onChange={e=>{K(e.target.value);P(false)}}><option value="Square">s(t) = t²</option><option value="Cubic">s(t) = t³/3</option><option value="Sine">s(t) = sin t</option></select></label><Slider label="First time t" value={a} onChange={v=>{A(v);P(false)}} min={-3} max={4} step={.05}/><Slider label="Time separation Δt" value={h} onChange={v=>{H(v);P(false)}} min={-2} max={2} step={.01}/><button className="primary" onClick={()=>{if(h===0)H(1);P(!playing)}}>{playing?'Pause motion':'Animate secant → tangent'}</button><button className="secondary" onClick={()=>{P(false);H(round(h/2,5))}}>Move halfway closer</button><div className="control-divider"/><p className="muted">Δs = {round(f(a+h)-f(a),4)} m<br/>First position = {round(f(a),4)} m<br/>Second position = {round(f(a+h),4)} m</p><Formula tex={h===0?'\\frac{0}{0}\\text{ is undefined}':`\\frac{\\Delta s}{\\Delta t}=\\frac{${round(f(a+h)-f(a),4)}}{${round(h,4)}}\\approx${round(sec,4)}`}/><button className="secondary" onClick={()=>set({a:0,b:.05,func:'Square',playing:false})}>Find a stationary point</button></>}>
<svg viewBox="0 0 600 400" className="svg-stage" role="img" aria-label="Position versus time graph with draggable secant endpoints" onPointerMove={move} onPointerUp={()=>D(null)} onPointerCancel={()=>D(null)}><defs><clipPath id="derivative-clip"><rect x="20" y="30" width="560" height="335"/></clipPath></defs><g clipPath="url(#derivative-clip)">{Array.from({length:11},(_,i)=><path key={i} d={`M${sx(i-5)} 25V365M25 ${sy(i-3)}H575`} stroke="#dce6d3" strokeWidth=".7"/>)}<path d={`M25 280H575M300 25V365`} stroke="#95aa83"/><path d={curve} fill="none" stroke={G} strokeWidth="3"/><path d={line(tan)} fill="none" stroke={B} strokeDasharray="7 4" strokeWidth="2"/>{h!==0&&<path d={line(sec)} fill="none" stroke={O} strokeWidth="2.5"/>}<path d={`M${sx(a)} ${sy(f(a))}H${sx(a+h)}V${sy(f(a+h))}`} fill="none" stroke={O} strokeDasharray="4 3"/>{[['a',a,G],['h',a+h,O]].map(([id,x,color])=><circle key={String(id)} cx={sx(Number(x))} cy={sy(f(Number(x)))} r="9" fill={String(color)} className="svg-click" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);D(id as 'a'|'h')}}/>)}<text x="535" y="302">time t (s)</text><text x="35" y="50">position s (m)</text></g><text x="300" y="386" textAnchor="middle">Green: position · Gold: average rate · Dashed blue: instantaneous rate</text></svg>
</Shell>}

