import {useState,useRef,useMemo,type ReactNode} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Edges,Line} from '@react-three/drei';
import * as THREE from 'three';
import {Shell} from './Labs';
import {useLab,useParam} from './parameters';
import {StudioCanvas} from './SpatialScenes';
import VolumeStory from './VolumeStory';
import SolidDiagram from './SolidDiagram';
import {Slider,Stage,colors} from './components';
import type {Topic} from './data';
import {solidMeasures} from './solidMath.mjs';
import {SceneLabel} from './SpatialScenes';
import {round} from './math.mjs';
function Face({s,position=[0,0,0],color='#b8d0a4'}:{s:number;position?:[number,number,number];color?:string}){return <mesh position={position}><planeGeometry args={[s,s]}/><meshStandardMaterial color={color} side={THREE.DoubleSide} roughness={.6}/><Edges color="#4f7750"/></mesh>}
function CubeNet({s,unfold}:{s:number;unfold:boolean}){const left=useRef<THREE.Group>(null),right=useRef<THREE.Group>(null),top=useRef<THREE.Group>(null),bottom=useRef<THREE.Group>(null),lid=useRef<THREE.Group>(null);useFrame((_,dt)=>{const theta=unfold?0:Math.PI/2;for(const [ref,axis,sign] of [[left,'y',-1],[right,'y',1],[top,'x',-1],[bottom,'x',1],[lid,'x',-1]] as const){if(ref.current)ref.current.rotation[axis]=THREE.MathUtils.damp(ref.current.rotation[axis],sign*theta,8,dt)}});return <group position={[0,-.4,s/2]}><Face s={s}/><group ref={left} position={[-s/2,0,0]} rotation={[0,-Math.PI/2,0]}><Face s={s} position={[-s/2,0,0]}/></group><group ref={right} position={[s/2,0,0]} rotation={[0,Math.PI/2,0]}><Face s={s} position={[s/2,0,0]}/></group><group ref={bottom} position={[0,-s/2,0]} rotation={[Math.PI/2,0,0]}><Face s={s} position={[0,-s/2,0]}/></group><group ref={top} position={[0,s/2,0]} rotation={[-Math.PI/2,0,0]}><Face s={s} position={[0,s/2,0]}/><group ref={lid} position={[0,s,0]} rotation={[-Math.PI/2,0,0]}><Face s={s} position={[0,s/2,0]} color="#d7b888"/></group></group></group>}
function Arrow({v,color}:{v:[number,number,number];color:string}){const obj=useMemo(()=>{const dir=new THREE.Vector3(...v),len=dir.length();return new THREE.ArrowHelper(len?dir.clone().normalize():new THREE.Vector3(1,0,0),new THREE.Vector3(),len,color,.2,.1)},[...v,color]);return <primitive object={obj}/>}
function Conic({angle,offset}:{angle:number;offset:number}){const slope=Math.tan(angle*Math.PI/180);const curves=useMemo(()=>{const chunks:[number,number,number][][]=[];for(const sign of [-1,1]){let chunk:[number,number,number][]=[];for(let i=0;i<=720;i++){const phi=i*Math.PI/360,den=sign-slope*Math.cos(phi),r=offset/den;if(r>0&&r<=2&&Number.isFinite(r)){chunk.push([r*Math.cos(phi),sign*r,r*Math.sin(phi)])}else if(chunk.length){if(chunk.length>1)chunks.push(chunk);chunk=[]}}if(chunk.length>1)chunks.push(chunk)}return chunks},[angle,offset]);return <><mesh position={[0,1,0]} rotation={[Math.PI,0,0]}><coneGeometry args={[2,2,48,1,true]}/><meshStandardMaterial color="#8aac7d" transparent opacity={.2} side={THREE.DoubleSide} depthWrite={false}/><Edges threshold={30} color="#88a57a"/></mesh><mesh position={[0,-1,0]}><coneGeometry args={[2,2,48,1,true]}/><meshStandardMaterial color="#8aac7d" transparent opacity={.2} side={THREE.DoubleSide} depthWrite={false}/></mesh><group position={[0,offset,0]} rotation={[0,0,angle*Math.PI/180]}><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[6,6]}/><meshStandardMaterial color="#d6a568" transparent opacity={.25} side={THREE.DoubleSide} depthWrite={false}/></mesh></group>{curves.map((c,i)=><Line key={i} points={c} color="#cb8039" lineWidth={3}/>)}</>}
function SafeCanvas({children,auto}:{children:ReactNode;auto:boolean}){return <StudioCanvas auto={auto} ground={-2.4}>{children}</StudioCanvas>}
export default function Solids({topic:t}:{topic:Topic}){const {setView}=useLab();const [labels,Labels]=useParam('labels',true),[explode,Explode]=useParam('explode',0),[top,Top]=useParam('top',.7),[fill,Fill]=useParam('fill',.5),[slice,Slice]=useParam('slice',false),[units,Units]=useParam('units',false),[shape,S]=useParam('shape',t.id==='volume'?'Cylinder':'Cube'),[r,R]=useParam('r',1.4),[h,H]=useParam('h',2.5),[transparent,T]=useParam('transparent',false),[auto,A]=useParam('auto',false),[unfold,U]=useParam('unfold',false),[x,X]=useParam('x',2),[y,Y]=useParam('y',2),[z,Z]=useParam('z',1),[angle,Angle]=useParam('angle',20),[offset,Offset]=useParam('offset',.7);const special=['net','vector','conic'].includes(t.id);const {volume,area}=solidMeasures(shape,r,h,Math.min(top,r));let visual:ReactNode;const s=r;
if(t.id==='net')visual=<CubeNet s={s} unfold={unfold}/>;
else if(t.id==='vector')visual=<><axesHelper args={[5]}/><Arrow v={[x,y,z]} color="#356f4a"/><Arrow v={[x,0,0]} color="#c48950"/><Arrow v={[0,y,0]} color="#719bc2"/><Arrow v={[0,0,z]} color="#b998c5"/><Line points={[[x,0,0],[x,y,0],[x,y,z]]} color="#71856a" dashed dashSize={.1}/></>;
else if(t.id==='conic')visual=<Conic angle={angle} offset={offset}/>;
else if(shape==='Cube'&&explode>0)visual=<>{[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]].map(([x,y,z],i)=><group key={i} position={[x*(r/2+explode),y*(r/2+explode),z*(r/2+explode)]} rotation={x?[0,Math.PI/2,0]:y?[Math.PI/2,0,0]:[0,0,0]}><Face s={r}/></group>)}</>;else if(shape==='Hemisphere')visual=<group><mesh castShadow><sphereGeometry args={[r,36,24,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color="#91b67e" transparent={transparent} opacity={transparent?.35:1} side={THREE.DoubleSide}/></mesh><mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[r,36]}/><meshStandardMaterial color="#b6cd9e" side={THREE.DoubleSide}/></mesh></group>;else visual=<mesh castShadow receiveShadow>{shape==='Cube'?<boxGeometry args={[r,r,r]}/>:shape==='Cuboid'?<boxGeometry args={[r,h,r]}/>:shape==='Sphere'?<sphereGeometry args={[r,36,24]}/>:shape==='Frustum'?<cylinderGeometry args={[Math.min(top,r),r,h,48]}/>:shape==='Cylinder'?<cylinderGeometry args={[r,r,h,36]}/>:<coneGeometry args={[r,h,36]}/>}<meshStandardMaterial color="#91b67e" transparent={transparent} opacity={transparent?.35:1} roughness={.55} side={THREE.DoubleSide}/><Edges threshold={25} color="#416b40"/></mesh>;
const metrics:[string,string|number][]=t.id==='vector'?[['Components',`(${x}, ${y}, ${z})`],['Magnitude',round(Math.hypot(x,y,z))],['Squared magnitude',x*x+y*y+z*z]]:t.id==='net'?[['Faces',6],['Surface area',`${round(6*s*s,2)} u²`],['State',unfold?'Flat net':'Folded cube']]:t.id==='conic'?[['Plane angle',`${angle}°`],['Intersection',angle===0?'Circle':angle<45?'Ellipse':angle===45?'Parabola':'Hyperbola'],['Offset',offset]]:[['Volume',`${round(volume,2)} u³`],['Surface area',`${round(area,2)} u²`],['Shape',shape]];
return <Shell spatial={<SafeCanvas auto={auto}>{visual}{labels&&!special&&<SceneLabel at={[0,Math.max(r,h)/2+1,0]}>{shape} · {shape==='Cube'?'side':'radius'} {r} u{!['Cube','Sphere','Hemisphere'].includes(shape)?' · height '+h+' u':''}</SceneLabel>}{!special&&t.id==='volume'&&<VolumeStory/>}</SafeCanvas>} metrics={metrics} note={`${t.learn} Drag to orbit; scroll or pinch to zoom; right-drag to pan.`} controls={<>{!special&&<><label className="control-select">Solid<select value={shape} onChange={e=>S(e.target.value)}>{['Cube','Cuboid','Sphere','Hemisphere','Cylinder','Cone','Frustum'].map(s=><option key={s}>{s}</option>)}</select></label><Slider label={shape==='Cube'||shape==='Cuboid'?'Side / width':'Radius'} value={r} onChange={R} min={.5} max={5} step={.1}/>{!['Cube','Sphere','Hemisphere'].includes(shape)&&<Slider label="Height" value={h} onChange={H} min={.5} max={4} step={.1}/>}{t.id==='volume'&&['Cube','Cuboid','Cylinder'].includes(shape)&&<><Slider label="Fill proportion" value={fill} onChange={v=>{Fill(v);T(true)}} min={0} max={1} step={.05}/><label className="toggle-row">Show cross-section<input type="checkbox" checked={slice} onChange={e=>{Slice(e.target.checked);T(true)}}/></label>{shape==='Cube'&&<label className="toggle-row">Show unit cubes (integer part)<input type="checkbox" checked={units} onChange={e=>{Units(e.target.checked);T(true)}}/></label>}</>}{shape==='Frustum'&&<Slider label="Top radius" value={Math.min(top,r)} onChange={Top} min={.1} max={r} step={.1}/>} {shape==='Cube'&&<Slider label="Separate the six faces" value={explode} onChange={Explode} min={0} max={1} step={.1}/>}<label className="toggle-row">Transparent<input type="checkbox" checked={transparent} onChange={e=>T(e.target.checked)}/></label></>}{t.id==='net'&&<><Slider label="Side length" value={r} onChange={R} min={.5} max={2} step={.1}/><button className="primary" onClick={()=>U(!unfold)}>{unfold?'Fold into cube':'Unfold into net'}</button></>}{t.id==='vector'&&<>{[['x',x,X],['y',y,Y],['z',z,Z]].map(([label,val,set])=><Slider key={label as string} label={`${label} component`} value={val as number} onChange={set as (v:number)=>void} min={-6} max={6}/>)}</>}{t.id==='conic'&&<><Slider label="Plane angle" value={angle} onChange={Angle} min={0} max={70}/><Slider label="Plane offset" value={offset} onChange={Offset} min={.2} max={1.5} step={.1}/><div className="button-row">{[0,25,45,60].map(v=><button key={v} onClick={()=>Angle(v)}>{v}°</button>)}</div><p className="muted" style={{marginTop:15}}>Cone half-angle: 45°. Only the portion inside the finite double cone is drawn.</p></>}<label className="toggle-row">Show dimension labels<input type="checkbox" checked={labels} onChange={e=>Labels(e.target.checked)}/></label><label className="toggle-row">Auto-rotate<input type="checkbox" checked={auto} onChange={e=>A(e.target.checked)}/></label><button className="secondary" onClick={()=>setView('2D')}>Use 2D measurement view</button></>}>
<SolidDiagram/>
</Shell>}


