import {useMemo,useRef,useState,useEffect,type ReactNode} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,ContactShadows,Html,Line,Edges} from '@react-three/drei';
import * as THREE from 'three';
import {useLab} from './parameters';
import {useDarkTheme} from './useTheme';
import {round,triangleCenters} from './math.mjs';
const GREEN='#44836c',GOLD='#dda759',BLUE='#718db9';
export function SceneLabel({at,children}:{at:[number,number,number];children:ReactNode}){const dark=useDarkTheme();const text=Array.isArray(children)?children.map(String).join(''):String(children);const {texture,width}=useMemo(()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d')!;ctx.font='24px Segoe UI';const width=Math.max(160,Math.ceil(ctx.measureText(text).width)+36);canvas.width=width;canvas.height=60;ctx.fillStyle=dark?'#203955':'#ffffed';ctx.beginPath();ctx.roundRect(0,0,width,60,10);ctx.fill();ctx.strokeStyle=dark?'#526e8e':'#becfb5';ctx.stroke();ctx.fillStyle=dark?'#edf3fc':'#294f3e';ctx.font='24px Segoe UI';ctx.textBaseline='middle';ctx.textAlign='center';ctx.fillText(text,width/2,30);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return {texture,width}},[text,dark]);useEffect(()=>()=>texture.dispose(),[texture]);return <sprite position={at} scale={[width/150,.4,1]} renderOrder={10}><spriteMaterial map={texture} depthTest={false} transparent/></sprite>}
export function StudioCanvas({children,auto=false,table=true,ground=0}:{children:ReactNode;auto?:boolean;table?:boolean;ground?:number}){const dark=useDarkTheme();return <div className="studio-canvas" data-testid="spatial-canvas"><Canvas shadows dpr={[1,1.5]} camera={{position:[6,6,8],fov:42}} gl={{antialias:true,powerPreference:'low-power'}}><color attach="background" args={[dark?'#132339':'#f0f1e9']}/><ambientLight intensity={.8}/><hemisphereLight args={['#fff6e8','#a4b598',1.3]}/><directionalLight castShadow position={[4,9,5]} intensity={2.3} shadow-mapSize={[1024,1024]} shadow-camera-left={-9} shadow-camera-right={9} shadow-camera-top={9} shadow-camera-bottom={-9} shadow-bias={-.001}/>{children}{table&&<mesh receiveShadow position={[0,ground-.2,0]}><boxGeometry args={[11,.25,9]}/><meshStandardMaterial color={dark?'#354960':'#e3dbc6'} roughness={.8}/></mesh>}<ContactShadows position={[0,ground-.06,0]} opacity={.25} scale={12} blur={2.8} far={5} resolution={256}/><OrbitControls makeDefault enableDamping autoRotate={auto&&!matchMedia('(prefers-reduced-motion: reduce)').matches} minDistance={4} maxDistance={25}/></Canvas></div>}
function Block({position,color=GREEN,size=[.4,.4,.4],onClick}:{position:[number,number,number];color?:string;size?:[number,number,number];onClick?:()=>void}){return <mesh castShadow receiveShadow position={position} onClick={onClick}><boxGeometry args={size}/><meshStandardMaterial color={color} roughness={.48}/><Edges color="#496b5a"/></mesh>}
function Blocks({count,cols=10,origin=[0,0,0],color=GREEN}:{count:number;cols?:number;origin?:[number,number,number];color?:string}){return <>{Array.from({length:Math.max(0,Math.min(160,Math.round(count)))},(_,i)=><Block key={i} color={color} position={[origin[0]+i%cols*.48,origin[1]+.2,origin[2]+Math.floor(i/cols)*.48]}/>)}</>}
export function FlatShape({points,color=GREEN,height=.08}:{points:number[][];color?:string;height?:number}){const shape=useMemo(()=>{const s=new THREE.Shape();points.forEach((p,i)=>i?s.lineTo(p[0],p[1]):s.moveTo(p[0],p[1]));s.closePath();return s},[JSON.stringify(points)]);return <mesh castShadow receiveShadow rotation={[-Math.PI/2,0,0]}><extrudeGeometry args={[shape,{depth:height,bevelEnabled:false}]}/><meshStandardMaterial color={color} roughness={.6}/><Edges color="#496d58"/></mesh>}
function Pizza({second=false}:{second?:boolean}){const {values:p,set}=useLab(),n=Number(p[second?'cn':'n']),d=Number(p[second?'cd':'d']),factor=p.subdivide?Number(p.factor):1;const parts=d*factor,wholeCount=Math.max(1,Math.ceil(n/d)),explode=Number(p.explode||0);return <>{Array.from({length:wholeCount},(_,w)=>{const cx=wholeCount===1?0:(w-.5)*4;return <group key={w} position={[cx,0,0]}><mesh receiveShadow position={[0,.04,0]}><cylinderGeometry args={[1.95,1.95,.13,64]}/><meshStandardMaterial color="#f9f5e8" roughness={.4}/></mesh>{Array.from({length:parts},(_,i)=>{const theta=i*2*Math.PI/parts,mid=theta+Math.PI/parts,selected=w*d*factor+i<n*factor;return <group key={i} position={[Math.sin(mid)*explode,.15+(selected ? .08 : 0),Math.cos(mid)*explode]}><mesh castShadow onClick={()=>set({[second?'cn':'n']:Math.min(2*d,Math.ceil((w*parts+i+1)/factor))})}><cylinderGeometry args={[1.65,1.65,.2,Math.max(6,Math.ceil(48/parts)),1,false,theta+.015,2*Math.PI/parts-.03]}/><meshStandardMaterial color={selected?'#e6bd69':'#ebe7d9'} transparent={!selected} opacity={selected?1:.32} roughness={.65}/></mesh>{selected&&parts<=24&&<><mesh castShadow position={[Math.sin(mid)*.95,.13,Math.cos(mid)*.95]} rotation={[-Math.PI/2,0,0]}><cylinderGeometry args={[.14,.14,.025,12]}/><meshStandardMaterial color="#b9643e"/></mesh><mesh position={[Math.sin(mid)*1.25,.13,Math.cos(mid)*1.25]}><sphereGeometry args={[.055,8,8]}/><meshStandardMaterial color="#697e38"/></mesh></>}</group>})}<SceneLabel at={[0,1.4,-1.5]}>{Math.min(d,Math.max(0,n-w*d))}/{d} of this pizza</SceneLabel></group>})}</>}
export function PythagorasWorld(){const {values:p}=useLab(),a=Number(p.a),b=Number(p.b),scale=5/(a+b+Math.max(a,b));if(Number(p.proofStep)>0){const L=a+b,after=Number(p.proofStep)>=2;const pieces=after?[[[a,0],[L,0],[L,a]],[[a,0],[a,a],[L,a]],[[0,a],[a,a],[a,L]],[[0,a],[0,L],[a,L]]]:[[[0,0],[a,0],[0,b]],[[a,0],[L,0],[L,a]],[[L,a],[L,L],[b,L]],[[0,b],[b,L],[0,L]]];return <group scale={5/L} position={[-2.5,.15,2.5]}><FlatShape points={[[0,0],[L,0],[L,L],[0,L]]} color="#d7e4c7" height={.05}/>{pieces.map((pts,i)=><group key={i} position={[0,.08,0]}><FlatShape points={pts} color={GOLD} height={.12}/></group>)}<SceneLabel at={[L/2,.8,-L/2]}>{after?'Uncovered area: a² + b²':'Uncovered area: c²'} = {round(a*a+b*b,2)}</SceneLabel></group>}return <group scale={scale} position={[-(a-b)*scale/2,.1,b*scale/2]}><FlatShape points={[[0,0],[a,0],[a,-a],[0,-a]]} color={GREEN}/><FlatShape points={[[0,0],[0,b],[-b,b],[-b,0]]} color={GOLD}/><FlatShape points={[[a,0],[0,b],[b,a+b],[a+b,a]]} color={BLUE}/><FlatShape points={[[0,0],[a,0],[0,b]]} color="#f6f2e5" height={.12}/><SceneLabel at={[a/2,.4,a/2]}>a² = {round(a*a,2)}</SceneLabel><SceneLabel at={[-b/2,.4,-b/2]}>b² = {round(b*b,2)}</SceneLabel><SceneLabel at={[(a+b)/2,.4,-(a+b)/2]}>c² = {round(a*a+b*b,2)}</SceneLabel></group>}
export function MotionWorld(){const {values:p}=useLab(),a=Number(p.a),h=Number(p.b),mode=String(p.func||'Square');const f=(t:number)=>mode==='Cubic'?t**3/3:mode==='Sine'?Math.sin(t):t*t;const position=f(a),other=f(a+h),length=8;const low=Math.min(0,position,other),high=Math.max(1,position,other);const normalize=(v:number)=>-1+(v-low)/(high-low)*6;return <><mesh receiveShadow position={[0,.02,0]}><boxGeometry args={[length,.08,1.4]}/><meshStandardMaterial color="#536459"/></mesh>{Array.from({length:15},(_,i)=><mesh key={i} rotation={[-Math.PI/2,0,0]} position={[-3.6+i*.5,.07,0]}><planeGeometry args={[.23,.05]}/><meshBasicMaterial color="#f7ecd4"/></mesh>)}<Car at={[normalize(position)-2,.22,0]} color={GREEN}/><Car at={[normalize(other)-2,.22,.8]} color={GOLD}/><Line points={[[normalize(position)-2,.12,-.8],[normalize(other)-2,.12,-.8]]} color={GOLD} lineWidth={3}/><SceneLabel at={[-1,1.8,-1]}>Position s(t) = {mode==='Square'?'t²':mode==='Cubic'?'t³/3':'sin t'}</SceneLabel><SceneLabel at={[-2,1.1,1.5]}>t = {round(a,2)} s · s = {round(position,2)} m</SceneLabel><SceneLabel at={[2,1.1,1.5]}>t + Δt = {round(a+h,3)} s · s = {round(other,3)} m</SceneLabel></>}
function Car({at,color}:{at:[number,number,number];color:string}){const group=useRef<THREE.Group>(null);useFrame((_,dt)=>{if(group.current){const target=new THREE.Vector3(...at);group.current.position.lerp(target,matchMedia('(prefers-reduced-motion: reduce)').matches?1:1-Math.exp(-dt*8))}});return <group ref={group} position={at}><mesh castShadow><boxGeometry args={[.65,.25,.35]}/><meshStandardMaterial color={color} roughness={.4}/></mesh><mesh castShadow position={[0,.2,0]}><boxGeometry args={[.32,.22,.3]}/><meshStandardMaterial color="#c3d4cc" metalness={.15} roughness={.2}/></mesh>{[-.21,.21].flatMap(x=>[-.19,.19].map(z=><mesh key={`${x}-${z}`} position={[x,-.12,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.09,.09,.045,12]}/><meshStandardMaterial color="#39463f"/></mesh>))}</group>}
function PlotWorld(){const {topic,values:p}=useLab(),a=Number(p.a),b=Number(p.b),kind=String(p.func);const scale=.6;const f=(x:number)=>topic.id==='quadratic'?a*x*x+b*x+Number(p.c):topic.id==='graph'?(kind==='Quadratic'?a*x*x+b:kind==='Sine'?a*Math.sin(x)+b:kind==='Cubic'?a*x*x*x+b:a*x+b):x*x;const chunks:[number,number,number][][]=[];let chunk:[number,number,number][]=[];for(let i=0;i<=160;i++){const x=-4+i/20,y=f(x);if(Math.abs(y*scale)<4.5){chunk.push([x*scale,.12,-y*scale])}else{if(chunk.length>1)chunks.push(chunk);chunk=[]}}if(chunk.length>1)chunks.push(chunk);return <><gridHelper args={[8,16,'#6e967d','#b0c4ae']} position={[0,.02,0]}/><Line points={[[-4,.07,0],[4,.07,0]]} color={GREEN}/><Line points={[[0,.07,-4],[0,.07,4]]} color={BLUE}/>{topic.id==='coordinate'?<><Block position={[a*scale,.25,-b*scale]} color={GOLD}/><SceneLabel at={[a*scale,1,-b*scale]}>({a}, {b})</SceneLabel></>:<><>{chunks.map((points,i)=><Line key={i} points={points} color={GREEN} lineWidth={4}/>)}</>{topic.id==='limit'&&<Block position={[(a+b)*scale,.3,-((a+b)**2)*scale]} color={GOLD}/>}<SceneLabel at={[0,1.8,-3]}>A coordinate board in space — the same x / y relationship</SceneLabel></>}{topic.id==='integral'&&Array.from({length:Math.min(40,Number(p.n))},(_,i)=>{const left=Math.min(a,b),right=Math.max(a,b),dx=(right-left)/Math.min(40,Number(p.n)),x=left+(i+.5)*dx;return <Block key={i} position={[x*scale,.12,-x*x*scale/2]} size={[dx*scale*.95,.16,x*x*scale]} color={GOLD}/>})}</>}
function Content(){const {topic,values:p,set}=useLab(),a=Number(p.a),b=Number(p.b),id=topic.id;if(id==='fraction')return p.compare?<><group position={[-2.4,0,0]} scale={.65}><Pizza/></group><group position={[2.4,0,0]} scale={.65}><Pizza second/></group><SceneLabel at={[0,1.6,-2]}>Compare equal wholes: {String(p.n)}/{String(p.d)} and {String(p.cn)}/{String(p.cd)}</SceneLabel></>:<Pizza/>;if(id==='pythagoras')return <PythagorasWorld/>;if(id==='derivative')return <MotionWorld/>;
if(id==='number')return <><Line points={[[-4,.1,0],[4,.1,0]]} color={GREEN}/>{Array.from({length:21},(_,i)=><group key={i} position={[(i-10)*.4,0,0]}><Block position={[0,.15,0]} size={[.035,.3,.1]} color="#bdc6b3"/><SceneLabel at={[0,.05,1]}>{i-10}</SceneLabel></group>)}<Block position={[a*.4,.55,0]} color={GOLD}/><SceneLabel at={[a*.4,1.5,0]}>Position {a}</SceneLabel></>;
if(id==='place'){const h=Math.floor(a/100),t=Math.floor(a%100/10),u=a%10;return <><Blocks count={h} cols={3} origin={[-3,0,0]}/>{Array.from({length:t},(_,i)=><Block key={i} position={[-.8+i*.25,.4,0]} size={[.15,.8,.15]} color={GOLD}/>)}<Blocks count={u} cols={3} origin={[2,0,0]} color={BLUE}/><SceneLabel at={[-2,1.7,0]}>{h} hundred blocks · each = 100</SceneLabel><SceneLabel at={[0,1.7,1]}>{t} ten rods</SceneLabel><SceneLabel at={[2.8,1.7,0]}>{u} units</SceneLabel></>}
if(id==='percentage')return <>{Array.from({length:100},(_,i)=><Block key={i} position={[-2.3+i%10*.48,.22,-2+Math.floor(i/10)*.48]} color={i<a?GREEN:'#dcdccf'} onClick={()=>set({a:i+1})}/>)}<SceneLabel at={[0,1.7,-2]}>Select blocks · {a} / 100 = {a}%</SceneLabel></>;
if(id==='array'||id==='area')return <><Blocks count={a*b} cols={id==='array'?b:a} origin={[-2,0,-1.5]}/><SceneLabel at={[0,1.7,-2]}>{a} × {b} = {a*b} unit {id==='area'?'squares':'blocks'}</SceneLabel></>;
if(id==='division')return <>{Array.from({length:b},(_,i)=><group key={i} position={[-3+i*6/b,0,0]}><mesh position={[0,.04,0]}><cylinderGeometry args={[.48,.48,.08,24]}/><meshStandardMaterial color="#eee8d6"/></mesh><Blocks count={Math.floor(a/b)} cols={2} origin={[-.2,.08,0]}/></group>)}<Blocks count={a%b} origin={[-2,0,2]} color={GOLD}/><SceneLabel at={[0,1.8,-2]}>{a} shared into {b} groups · remainder {a%b}</SceneLabel></>;
if(id==='addition'||id==='ratio')return <><Blocks count={a} cols={5} origin={[-3,0,0]}/><Blocks count={b} cols={5} origin={[.6,0,0]} color={GOLD}/><SceneLabel at={[0,1.8,-1]}>{id==='ratio'?`${a} green : ${b} gold`:`${a} ${p.operation==='Subtract'?'−':'+'} ${b} = ${p.operation==='Subtract'?a-b:a+b}`}</SceneLabel></>;
if(id==='balance')return <><mesh castShadow position={[0,.7,0]}><coneGeometry args={[.5,1.4,4]}/><meshStandardMaterial color="#8b9e84"/></mesh><Block position={[0,1.45,0]} size={[6,.12,.2]} color="#8b9e84"/><Block position={[-2,.65,0]} size={[1.7,.12,1.7]} color="#d9c9a6"/><Block position={[2,.65,0]} size={[1.7,.12,1.7]} color="#d9c9a6"/><Block position={[-2,.95,0]} size={[.65,.55,.6]}/><Blocks count={p.removed?0:a} cols={3} origin={[-2.6,.8,.8]} color={GOLD}/><Blocks count={p.removed?b:a+b} cols={4} origin={[1.2,.8,.4]} color={GOLD}/><SceneLabel at={[0,2.2,0]}>{p.removed?`x = ${b}`:`x + ${a} = ${a+b}`} · both sides balance</SceneLabel></>;
if(id==='triangle'){const pts=p.points as number[][],cx=pts.reduce((s,v)=>s+v[0],0)/3,cy=pts.reduce((s,v)=>s+v[1],0)/3;return <><FlatShape points={pts.map(v=>[(v[0]-cx)/65,(v[1]-cy)/65])} color={GREEN}/>{p.proof&&(()=>{const centers=triangleCenters(pts),key=String(p.centerMode||'Centroid'),center=key==='Incenter'?centers.incenter:key==='Circumcenter'?centers.circumcenter:key==='Orthocenter'?centers.orthocenter:centers.centroid;return center&&<><Block position={[(center[0]-cx)/65,.2,-(center[1]-cy)/65]} size={[.13,.3,.13]} color={GOLD}/><SceneLabel at={[(center[0]-cx)/65,.9,-(center[1]-cy)/65]}>{key}</SceneLabel></>})()}{pts.map((v,i)=><SceneLabel key={i} at={[(v[0]-cx)/65,.4,-(v[1]-cy)/65]}>{'ABC'[i]}</SceneLabel>)}</>}
if(id==='circle'||id==='angle'||id==='trig'){const rad=a*Math.PI/180;if(id==='circle')return <><mesh castShadow position={[0,.12,0]}><cylinderGeometry args={[a*.25,a*.25,.2,64]}/><meshStandardMaterial color="#8faf87"/></mesh><Line points={[[0,.24,0],[a*.25,.24,0]]} color={GOLD} lineWidth={3}/><SceneLabel at={[0,1.4,0]}>Radius {a} · Area {round(Math.PI*a*a,2)}</SceneLabel></>;return <><Line points={Array.from({length:65},(_,i)=>[2*Math.cos(i*Math.PI/32),.1,-2*Math.sin(i*Math.PI/32)] as [number,number,number])} color="#9cad91"/><Line points={[[2,.15,0],[0,.15,0],[2*Math.cos(rad),.15,-2*Math.sin(rad)]]} color={GREEN} lineWidth={4}/><Block position={[2*Math.cos(rad),.3,-2*Math.sin(rad)]} color={GOLD}/><SceneLabel at={[0,1.6,0]}>θ = {a}°{id==='trig'?` · sin θ = ${round(Math.sin(rad))}`:''}</SceneLabel></>}
if(['coordinate','graph','limit','integral'].includes(id))return <PlotWorld/>;
if(id==='statistics'){const vals=String(p.text).split(/[\s,]+/).filter(Boolean).map(Number).filter(Number.isFinite).slice(0,40),max=Math.max(1,...vals.map(Math.abs));return <>{vals.map((v,i)=><Block key={i} position={[-3+i*6/vals.length,v/max*1.5,0]} size={[Math.max(.05,5/vals.length),Math.max(.02,Math.abs(v)/max*3),.6]} color={v<0?GOLD:GREEN}/>)}<SceneLabel at={[0,3.8,0]}>Signed columns · gold extends below the zero plane</SceneLabel></>}
if(id==='probability'){const values=p.outcomes as number[],count=p.experiment==='Coin'?2:6;return <>{values.slice(0,count).map((v,i)=><group key={i} position={[-2.5+i*5/Math.max(1,count-1),0,0]}>{p.experiment==='Coin'?<mesh castShadow rotation={[Math.PI/2,0,0]} position={[0,.35,0]}><cylinderGeometry args={[.5,.5,.1,40]}/><meshStandardMaterial color={GOLD} metalness={.55} roughness={.4}/></mesh>:<Block position={[0,.4,0]} size={[.65,.65,.65]} color="#f3ecd9"/>}<SceneLabel at={[0,1.2,0]}>{p.experiment==='Coin'?['Heads','Tails'][i]:i+1}</SceneLabel><SceneLabel at={[0,.1,1.2]}>{v} observations</SceneLabel></group>)}</>}
if(id==='matrix'){const theta=a*Math.PI/180;const m=p.transform==='Rotate'?[Math.cos(theta),-Math.sin(theta),Math.sin(theta),Math.cos(theta)]:p.transform==='Reflect'?[-1,0,0,1]:p.transform==='Shear'?[1,a,0,1]:[a,0,0,b];return <><gridHelper args={[8,16,'#9bb193','#d0ddc8']}/><FlatShape points={[[0,0],[2,0],[2,2],[0,2]]} color="#d8ddcc"/><group position={[0,.12,0]}><FlatShape points={[[0,0],[2,0],[2,2],[0,2]].map(([x,y])=>[m[0]*x+m[1]*y,m[2]*x+m[3]*y])} color={GREEN}/></group><SceneLabel at={[0,2.5,0]}>One matrix changes every point</SceneLabel></>}
if(id==='commercial'&&p.mode==='Simple interest')return <><Blocks count={Number(p.time)} cols={5} origin={[-2,0,0]} color={GOLD}/><SceneLabel at={[0,1.8,-1]}>₹{a} + {String(p.time)} years × ₹{round(a*Number(p.rate)/100,2)} = ₹{round(a*(1+Number(p.rate)*Number(p.time)/100),2)}</SceneLabel></>;if(id==='commercial')return <><Block position={[-1,.4,0]} color={GREEN} size={[1,.8,1]}/><Block position={[1,.4,0]} color={GOLD} size={[1,.8,1]}/><SceneLabel at={[-1,1.4,0]}>Original ₹{a}</SceneLabel><SceneLabel at={[1,1.4,0]}>After {b}% discount: ₹{round(a*(1-b/100),2)}</SceneLabel></>;
if(id==='factors')return <><Blocks count={Math.min(a,100)} cols={b>0&&a%b===0?b:Math.ceil(Math.sqrt(a))} origin={[-2,0,-2]}/><SceneLabel at={[0,1.8,-2]}>Arrange {a} objects · test groups of {b}</SceneLabel></>;
if(id==='decimal')return <>{Array.from({length:100},(_,i)=><Block key={i} position={[-2.3+i%10*.48,.2,-2+Math.floor(i/10)*.48]} color={i<a?GREEN:'#dcdccf'}/>)}<SceneLabel at={[0,1.6,-2]}>{a} hundredths = {round(a/100,2)}</SceneLabel></>;
if(id==='sequence')return <>{Array.from({length:Number(p.n)},(_,i)=><Block key={i} position={[-2+i*.7,(a+i*b)/10,0]} size={[.5,Math.max(.05,Math.abs(a+i*b)/5),.5]}/>)}<SceneLabel at={[0,3,0]}>Equal changes make an arithmetic sequence</SceneLabel></>;
if(id==='quadratic')return <PlotWorld/>;return null}
export default function SpatialScenes(){const {values:p}=useLab();return <StudioCanvas auto={!!p.auto} table={useLab().topic.id!=='statistics'}><Content/></StudioCanvas>}




