import {useState,Suspense,lazy} from 'react';
import {topics,type Topic} from './data';
import {ParameterProvider,useLab,type Parameters,type ViewMode} from './parameters';
import {learningFor,type LearningPack} from './learning';
import {conceptsFor} from './concepts';
import {visualizationRegistry} from './registry';
import {relationship,formulaFor} from './relationships';
import {Formula} from './components';
import FractionLab from './FractionLab';
import {PythagorasLab,DerivativeLab} from './RepresentativeLabs';
import {gcd,round} from './math.mjs';
const FormulaLab=lazy(()=>import('./FormulaLab'));
const Trigonometry=lazy(()=>import('./TrigonometryLab'));
const Extended=lazy(()=>import('./ExtendedLabs'));
const Labs=lazy(()=>import('./Labs'));
const sections=['Understand','Explore','Formula','Why','Examples','Real life','Experiment','Practice','Challenge'];
import {checkActivity} from './activities.mjs';
function LiveRelationship(){const {topic,values}=useLab();return <div className="live-relationship" aria-live="polite"><small>LIVE SUBSTITUTION</small><strong>{relationship(topic,values)}</strong></div>}
function ExampleCard({example,index}:{example:LearningPack['examples'][number];index:number}){const {set}=useLab(),[step,S]=useState(0);return <article className="worked-example"><small>{example.label}</small><h3>{example.question}</h3><button onClick={()=>set(example.params)}>Load into the lab</button><ol>{example.steps.slice(0,step).map((s,i)=><li key={i}>{s}</li>)}</ol><button onClick={()=>S(Math.min(example.steps.length,step+1))} disabled={step===example.steps.length}>{step===example.steps.length?'All steps revealed':step===0?'Start explanation':'Reveal next step'}</button><span className="sr-only">Example {index+1}</span></article>}
function Experience({onOpen}:{onOpen:(t:Topic)=>void}){const {topic:t,section, setSection,view,setView,set,values}=useLab(),pack=learningFor(t),[prediction,P]=useState<number|null>(null),[observed,O]=useState(false),[feedback,F]=useState(''),[hint,H]=useState(false),[audience,A]=useState(t.classes[0]);const activity=section==='Challenge'?pack.challenge:pack.practice;const engine=t.id.startsWith('lab-')?<FormulaLab/>:visualizationRegistry[t.id].family==='representative'&&t.id==='fraction'?<FractionLab resetKey={0}/>:t.id==='pythagoras'?<PythagorasLab/>:t.id==='derivative'?<DerivativeLab/>:t.id==='trig'?<Trigonometry/>:['decimal','factors','commercial','quadratic','sequence'].includes(t.id)?<Extended/>:<Labs topic={t}/>;
return <><div className="topic-tabs" role="tablist" aria-label="Learning sections">{sections.map(s=><button key={s} role="tab" aria-selected={section===s} className={section===s?'selected':''} onClick={()=>{setSection(s);F('');H(false)}}>{s}</button>)}</div><div className="lab-toolbar"><div className="view-switch" role="group" aria-label="Visualization mode">{(['2D','3D','Split'] as ViewMode[]).map(v=><button key={v} aria-pressed={view===v} className={view===v?'selected':''} onClick={()=>setView(v)}>{v}</button>)}</div><span>One experiment · linked views</span><label>Concept <select aria-label="Micro-concept" defaultValue="" onChange={e=>{const c=conceptsFor(t.id).find(c=>c.id===e.target.value);if(c){set(c.preset);setSection('Explore')}}}><option value="" disabled>Choose a concept…</option>{conceptsFor(t.id).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Learning level <select aria-label="Learning class" value={audience} onChange={e=>A(Number(e.target.value))}>{t.classes.map(c=><option key={c} value={c}>Class {c}</option>)}</select></label></div>
{section==='Understand'&&<section className="lesson-panel"><span className="eyebrow">START WITH A QUESTION</span><h2>{pack.curiosity}</h2><p>{pack.simple}</p>{audience>=7&&<p><strong>Mathematical definition:</strong> {pack.formal}</p>}<p className="lesson-condition">{pack.condition}</p><button onClick={()=>setSection('Explore')}>Try it in the lab →</button></section>}
{section==='Formula'&&<section className="lesson-panel"><h2>The relationship behind the model</h2><Formula tex={formulaFor(t,values)}/><p>{pack.read}</p><div className="variable-table"><table><thead><tr><th>Symbol</th><th>Meaning</th><th>Unit</th></tr></thead><tbody>{pack.variables.map(([symbol,meaning,unit])=><tr key={symbol}><td>{symbol}</td><td>{meaning}</td><td>{unit}</td></tr>)}</tbody></table></div><LiveRelationship/><p><strong>When it applies:</strong> {pack.condition}</p><p className="misconception"><strong>Watch out:</strong> {pack.mistake}</p><button onClick={()=>{set(pack.examples[0].params);setSection('Examples')}}>See a worked example</button></section>}
{section==='Why'&&<section className="lesson-panel"><h2>Why does it work?</h2><p>{pack.why}</p><p className="misconception">{pack.mistake}</p>{t.id==='pythagoras'&&<button onClick={()=>set({proofStep:1})}>Start the rearrangement below</button>}{t.id==='fraction'&&<button onClick={()=>set({factor:2,subdivide:true})}>Split every piece into two</button>}{t.id==='derivative'&&<button onClick={()=>set({b:.05,func:'Square'})}>Bring the points closer</button>}</section>}
{section==='Examples'&&<div className="examples-grid">{pack.examples.map((e,i)=><ExampleCard key={`${t.id}-${i}`} example={e} index={i}/>)}</div>}
{section==='Real life'&&<section className="lesson-panel"><span className="eyebrow">MATHEMATICS AROUND YOU</span><h2>{pack.examples[2].question}</h2><p>{t.real}</p><p>{pack.examples[2].steps.join(' → ')}</p><button onClick={()=>set(pack.examples[2].params)}>Explore this scenario</button></section>}
{section==='Experiment'&&<section className="lesson-panel"><span className="eyebrow">PREDICT · CHANGE · OBSERVE · EXPLAIN</span><h2>{pack.experiment.question}</h2><div className="prediction-options">{pack.experiment.choices.map((c,i)=><button key={i} aria-pressed={prediction===i} className={prediction===i?'selected':''} onClick={()=>{P(i);O(false);set(pack.experiment.before)}}>{c}</button>)}</div><div className="button-row"><button onClick={()=>{set(pack.experiment.before);O(false)}}>Show before</button><button className="primary" disabled={prediction===null} onClick={()=>{set(pack.experiment.after);O(true)}}>Run experiment</button></div>{observed&&<p role="status"><strong>{prediction===pack.experiment.correct?'Your prediction matches.':'Compare your prediction with the result.'}</strong> {pack.experiment.explain}</p>}</section>}
{['Practice','Challenge'].includes(section)&&<section className="lesson-panel"><span className="eyebrow">{section.toUpperCase()} · BUILD YOUR ANSWER</span><h2>{activity.prompt}</h2><p>Use the lab controls or draggable points below. Checking reads the model you have built.</p><div className="button-row"><button className="primary" onClick={()=>{const ok=checkActivity(values,activity);F(ok?'Correct — your model satisfies the conditions.':'Keep exploring. Your current model does not yet meet every condition.');if(ok)try{localStorage.setItem(`vx-completed-${t.id}`, 'true')}catch{}}}>Check my model</button><button onClick={()=>H(!hint)}>{hint?'Hide hint':'Give me a hint'}</button></div>{hint&&<p>{activity.hint}</p>}<p role="status">{feedback}</p><LiveRelationship/></section>}
<div className={`${t.id.startsWith('lab-')?'formula-lab-layout':'lab-layout'} ${audience<=3?'foundation-lab':'advanced-lab'}`}><Suspense fallback={<div className="loading">Preparing your experiment…</div>}>{engine}</Suspense></div><section className="concept-connections"><div><small>BEFORE THIS</small>{pack.prerequisites.map(id=>{const x=topics.find(x=>x.id===id);return x&&<button key={id} onClick={()=>onOpen(x)}>{x.title} →</button>})}{!pack.prerequisites.length&&<p>Start here and explore at your own pace.</p>}</div><div><small>WHERE THIS LEADS</small>{pack.next.map(id=>{const x=topics.find(x=>x.id===id);return x&&<button key={id} onClick={()=>onOpen(x)}>{x.title} →</button>})}</div></section></>}
export default function TopicExperience({topic,initialSection,onOpen}:{topic:Topic;initialSection:string;onOpen:(t:Topic)=>void}){return <ParameterProvider topic={topic} initialSection={initialSection==='Learn'?'Understand':initialSection==='Interact'?'Explore':initialSection==='Proof'?'Why':initialSection}><Experience onOpen={onOpen}/></ParameterProvider>}
